// Code generated by ent, DO NOT EDIT.

package reimbursementrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the reimbursementrequest type in the database.
	Label = "reimbursement_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRawText holds the string denoting the raw_text field in the database.
	FieldRawText = "raw_text"
	// FieldCompanyName holds the string denoting the company_name field in the database.
	FieldCompanyName = "company_name"
	// FieldTaxID holds the string denoting the tax_id field in the database.
	FieldTaxID = "tax_id"
	// FieldBankAccount holds the string denoting the bank_account field in the database.
	FieldBankAccount = "bank_account"
	// FieldBankName holds the string denoting the bank_name field in the database.
	FieldBankName = "bank_name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPdfPath holds the string denoting the pdf_path field in the database.
	FieldPdfPath = "pdf_path"
	// FieldPdfFileName holds the string denoting the pdf_file_name field in the database.
	FieldPdfFileName = "pdf_file_name"
	// FieldPdfSize holds the string denoting the pdf_size field in the database.
	FieldPdfSize = "pdf_size"
	// FieldPdfSha256 holds the string denoting the pdf_sha256 field in the database.
	FieldPdfSha256 = "pdf_sha256"
	// FieldPdfUploadedAt holds the string denoting the pdf_uploaded_at field in the database.
	FieldPdfUploadedAt = "pdf_uploaded_at"
	// FieldHandledBy holds the string denoting the handled_by field in the database.
	FieldHandledBy = "handled_by"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldNotifiedAt holds the string denoting the notified_at field in the database.
	FieldNotifiedAt = "notified_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the reimbursementrequest in the database.
	Table = "reimbursement_requests"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "reimbursement_requests"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for reimbursementrequest fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldRawText,
	FieldCompanyName,
	FieldTaxID,
	FieldBankAccount,
	FieldBankName,
	FieldAddress,
	FieldAmount,
	FieldStatus,
	FieldPdfPath,
	FieldPdfFileName,
	FieldPdfSize,
	FieldPdfSha256,
	FieldPdfUploadedAt,
	FieldHandledBy,
	FieldCompletedAt,
	FieldNotifiedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRawText holds the default value on creation for the "raw_text" field.
	DefaultRawText string
	// CompanyNameValidator is a validator for the "company_name" field. It is called by the builders before save.
	CompanyNameValidator func(string) error
	// TaxIDValidator is a validator for the "tax_id" field. It is called by the builders before save.
	TaxIDValidator func(string) error
	// BankAccountValidator is a validator for the "bank_account" field. It is called by the builders before save.
	BankAccountValidator func(string) error
	// BankNameValidator is a validator for the "bank_name" field. It is called by the builders before save.
	BankNameValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPdfPath holds the default value on creation for the "pdf_path" field.
	DefaultPdfPath string
	// PdfPathValidator is a validator for the "pdf_path" field. It is called by the builders before save.
	PdfPathValidator func(string) error
	// DefaultPdfFileName holds the default value on creation for the "pdf_file_name" field.
	DefaultPdfFileName string
	// PdfFileNameValidator is a validator for the "pdf_file_name" field. It is called by the builders before save.
	PdfFileNameValidator func(string) error
	// DefaultPdfSize holds the default value on creation for the "pdf_size" field.
	DefaultPdfSize int64
	// DefaultPdfSha256 holds the default value on creation for the "pdf_sha256" field.
	DefaultPdfSha256 string
	// PdfSha256Validator is a validator for the "pdf_sha256" field. It is called by the builders before save.
	PdfSha256Validator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReimbursementRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRawText orders the results by the raw_text field.
func ByRawText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawText, opts...).ToFunc()
}

// ByCompanyName orders the results by the company_name field.
func ByCompanyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompanyName, opts...).ToFunc()
}

// ByTaxID orders the results by the tax_id field.
func ByTaxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxID, opts...).ToFunc()
}

// ByBankAccount orders the results by the bank_account field.
func ByBankAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccount, opts...).ToFunc()
}

// ByBankName orders the results by the bank_name field.
func ByBankName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankName, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPdfPath orders the results by the pdf_path field.
func ByPdfPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfPath, opts...).ToFunc()
}

// ByPdfFileName orders the results by the pdf_file_name field.
func ByPdfFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfFileName, opts...).ToFunc()
}

// ByPdfSize orders the results by the pdf_size field.
func ByPdfSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfSize, opts...).ToFunc()
}

// ByPdfSha256 orders the results by the pdf_sha256 field.
func ByPdfSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfSha256, opts...).ToFunc()
}

// ByPdfUploadedAt orders the results by the pdf_uploaded_at field.
func ByPdfUploadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfUploadedAt, opts...).ToFunc()
}

// ByHandledBy orders the results by the handled_by field.
func ByHandledBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandledBy, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByNotifiedAt orders the results by the notified_at field.
func ByNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifiedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
