// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentbalancehold"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentBalanceHoldCreate is the builder for creating a PaymentBalanceHold entity.
type PaymentBalanceHoldCreate struct {
	config
	mutation *PaymentBalanceHoldMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (_c *PaymentBalanceHoldCreate) SetOrderID(v int64) *PaymentBalanceHoldCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentBalanceHoldCreate) SetUserID(v int64) *PaymentBalanceHoldCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentBalanceHoldCreate) SetAmount(v float64) *PaymentBalanceHoldCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentBalanceHoldCreate) SetStatus(v string) *PaymentBalanceHoldCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableStatus(v *string) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PaymentBalanceHoldCreate) SetExpiresAt(v time.Time) *PaymentBalanceHoldCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *PaymentBalanceHoldCreate) SetCapturedAt(v time.Time) *PaymentBalanceHoldCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableCapturedAt(v *time.Time) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *PaymentBalanceHoldCreate) SetReleasedAt(v time.Time) *PaymentBalanceHoldCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableReleasedAt(v *time.Time) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetReleaseReason sets the "release_reason" field.
func (_c *PaymentBalanceHoldCreate) SetReleaseReason(v string) *PaymentBalanceHoldCreate {
	_c.mutation.SetReleaseReason(v)
	return _c
}

// SetNillableReleaseReason sets the "release_reason" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableReleaseReason(v *string) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetReleaseReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentBalanceHoldCreate) SetCreatedAt(v time.Time) *PaymentBalanceHoldCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableCreatedAt(v *time.Time) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentBalanceHoldCreate) SetUpdatedAt(v time.Time) *PaymentBalanceHoldCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentBalanceHoldCreate) SetNillableUpdatedAt(v *time.Time) *PaymentBalanceHoldCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_c *PaymentBalanceHoldCreate) SetOrder(v *PaymentOrder) *PaymentBalanceHoldCreate {
	return _c.SetOrderID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentBalanceHoldCreate) SetUser(v *User) *PaymentBalanceHoldCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentBalanceHoldMutation object of the builder.
func (_c *PaymentBalanceHoldCreate) Mutation() *PaymentBalanceHoldMutation {
	return _c.mutation
}

// Save creates the PaymentBalanceHold in the database.
func (_c *PaymentBalanceHoldCreate) Save(ctx context.Context) (*PaymentBalanceHold, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentBalanceHoldCreate) SaveX(ctx context.Context) *PaymentBalanceHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentBalanceHoldCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentBalanceHoldCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentBalanceHoldCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentbalancehold.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentbalancehold.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentbalancehold.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentBalanceHoldCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "PaymentBalanceHold.order_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentBalanceHold.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentBalanceHold.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentBalanceHold.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentbalancehold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentBalanceHold.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PaymentBalanceHold.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentBalanceHold.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentBalanceHold.updated_at"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "PaymentBalanceHold.order"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentBalanceHold.user"`)}
	}
	return nil
}

func (_c *PaymentBalanceHoldCreate) sqlSave(ctx context.Context) (*PaymentBalanceHold, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentBalanceHoldCreate) createSpec() (*PaymentBalanceHold, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentBalanceHold{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentbalancehold.Table, sqlgraph.NewFieldSpec(paymentbalancehold.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentbalancehold.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentbalancehold.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(paymentbalancehold.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(paymentbalancehold.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = &value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(paymentbalancehold.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	if value, ok := _c.mutation.ReleaseReason(); ok {
		_spec.SetField(paymentbalancehold.FieldReleaseReason, field.TypeString, value)
		_node.ReleaseReason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentbalancehold.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentbalancehold.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   paymentbalancehold.OrderTable,
			Columns: []string{paymentbalancehold.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentbalancehold.UserTable,
			Columns: []string{paymentbalancehold.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentBalanceHold.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentBalanceHoldUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentBalanceHoldCreate) OnConflict(opts ...sql.ConflictOption) *PaymentBalanceHoldUpsertOne {
	_c.conflict = opts
	return &PaymentBalanceHoldUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentBalanceHoldCreate) OnConflictColumns(columns ...string) *PaymentBalanceHoldUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentBalanceHoldUpsertOne{
		create: _c,
	}
}

type (
	// PaymentBalanceHoldUpsertOne is the builder for "upsert"-ing
	//  one PaymentBalanceHold node.
	PaymentBalanceHoldUpsertOne struct {
		create *PaymentBalanceHoldCreate
	}

	// PaymentBalanceHoldUpsert is the "OnConflict" setter.
	PaymentBalanceHoldUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *PaymentBalanceHoldUpsert) SetOrderID(v int64) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateOrderID() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldOrderID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentBalanceHoldUpsert) SetUserID(v int64) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateUserID() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentBalanceHoldUpsert) SetAmount(v float64) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateAmount() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentBalanceHoldUpsert) AddAmount(v float64) *PaymentBalanceHoldUpsert {
	u.Add(paymentbalancehold.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentBalanceHoldUpsert) SetStatus(v string) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateStatus() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentBalanceHoldUpsert) SetExpiresAt(v time.Time) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateExpiresAt() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldExpiresAt)
	return u
}

// SetCapturedAt sets the "captured_at" field.
func (u *PaymentBalanceHoldUpsert) SetCapturedAt(v time.Time) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldCapturedAt, v)
	return u
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateCapturedAt() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldCapturedAt)
	return u
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *PaymentBalanceHoldUpsert) ClearCapturedAt() *PaymentBalanceHoldUpsert {
	u.SetNull(paymentbalancehold.FieldCapturedAt)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *PaymentBalanceHoldUpsert) SetReleasedAt(v time.Time) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateReleasedAt() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *PaymentBalanceHoldUpsert) ClearReleasedAt() *PaymentBalanceHoldUpsert {
	u.SetNull(paymentbalancehold.FieldReleasedAt)
	return u
}

// SetReleaseReason sets the "release_reason" field.
func (u *PaymentBalanceHoldUpsert) SetReleaseReason(v string) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldReleaseReason, v)
	return u
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateReleaseReason() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldReleaseReason)
	return u
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *PaymentBalanceHoldUpsert) ClearReleaseReason() *PaymentBalanceHoldUpsert {
	u.SetNull(paymentbalancehold.FieldReleaseReason)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentBalanceHoldUpsert) SetUpdatedAt(v time.Time) *PaymentBalanceHoldUpsert {
	u.Set(paymentbalancehold.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsert) UpdateUpdatedAt() *PaymentBalanceHoldUpsert {
	u.SetExcluded(paymentbalancehold.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentBalanceHoldUpsertOne) UpdateNewValues() *PaymentBalanceHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentbalancehold.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentBalanceHoldUpsertOne) Ignore() *PaymentBalanceHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentBalanceHoldUpsertOne) DoNothing() *PaymentBalanceHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentBalanceHoldCreate.OnConflict
// documentation for more info.
func (u *PaymentBalanceHoldUpsertOne) Update(set func(*PaymentBalanceHoldUpsert)) *PaymentBalanceHoldUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentBalanceHoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PaymentBalanceHoldUpsertOne) SetOrderID(v int64) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateOrderID() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentBalanceHoldUpsertOne) SetUserID(v int64) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateUserID() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentBalanceHoldUpsertOne) SetAmount(v float64) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentBalanceHoldUpsertOne) AddAmount(v float64) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateAmount() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentBalanceHoldUpsertOne) SetStatus(v string) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateStatus() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentBalanceHoldUpsertOne) SetExpiresAt(v time.Time) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateExpiresAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *PaymentBalanceHoldUpsertOne) SetCapturedAt(v time.Time) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateCapturedAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *PaymentBalanceHoldUpsertOne) ClearCapturedAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearCapturedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *PaymentBalanceHoldUpsertOne) SetReleasedAt(v time.Time) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateReleasedAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *PaymentBalanceHoldUpsertOne) ClearReleasedAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearReleasedAt()
	})
}

// SetReleaseReason sets the "release_reason" field.
func (u *PaymentBalanceHoldUpsertOne) SetReleaseReason(v string) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetReleaseReason(v)
	})
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateReleaseReason() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateReleaseReason()
	})
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *PaymentBalanceHoldUpsertOne) ClearReleaseReason() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearReleaseReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentBalanceHoldUpsertOne) SetUpdatedAt(v time.Time) *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertOne) UpdateUpdatedAt() *PaymentBalanceHoldUpsertOne {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentBalanceHoldUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentBalanceHoldCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentBalanceHoldUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentBalanceHoldUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentBalanceHoldUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentBalanceHoldCreateBulk is the builder for creating many PaymentBalanceHold entities in bulk.
type PaymentBalanceHoldCreateBulk struct {
	config
	err      error
	builders []*PaymentBalanceHoldCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentBalanceHold entities in the database.
func (_c *PaymentBalanceHoldCreateBulk) Save(ctx context.Context) ([]*PaymentBalanceHold, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentBalanceHold, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentBalanceHoldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentBalanceHoldCreateBulk) SaveX(ctx context.Context) []*PaymentBalanceHold {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentBalanceHoldCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentBalanceHoldCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentBalanceHold.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentBalanceHoldUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentBalanceHoldCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentBalanceHoldUpsertBulk {
	_c.conflict = opts
	return &PaymentBalanceHoldUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentBalanceHoldCreateBulk) OnConflictColumns(columns ...string) *PaymentBalanceHoldUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentBalanceHoldUpsertBulk{
		create: _c,
	}
}

// PaymentBalanceHoldUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentBalanceHold nodes.
type PaymentBalanceHoldUpsertBulk struct {
	create *PaymentBalanceHoldCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentBalanceHoldUpsertBulk) UpdateNewValues() *PaymentBalanceHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentbalancehold.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentBalanceHold.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentBalanceHoldUpsertBulk) Ignore() *PaymentBalanceHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentBalanceHoldUpsertBulk) DoNothing() *PaymentBalanceHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentBalanceHoldCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentBalanceHoldUpsertBulk) Update(set func(*PaymentBalanceHoldUpsert)) *PaymentBalanceHoldUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentBalanceHoldUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *PaymentBalanceHoldUpsertBulk) SetOrderID(v int64) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateOrderID() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentBalanceHoldUpsertBulk) SetUserID(v int64) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateUserID() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentBalanceHoldUpsertBulk) SetAmount(v float64) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentBalanceHoldUpsertBulk) AddAmount(v float64) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateAmount() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentBalanceHoldUpsertBulk) SetStatus(v string) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateStatus() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PaymentBalanceHoldUpsertBulk) SetExpiresAt(v time.Time) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateExpiresAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *PaymentBalanceHoldUpsertBulk) SetCapturedAt(v time.Time) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateCapturedAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateCapturedAt()
	})
}

// ClearCapturedAt clears the value of the "captured_at" field.
func (u *PaymentBalanceHoldUpsertBulk) ClearCapturedAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearCapturedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *PaymentBalanceHoldUpsertBulk) SetReleasedAt(v time.Time) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateReleasedAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *PaymentBalanceHoldUpsertBulk) ClearReleasedAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearReleasedAt()
	})
}

// SetReleaseReason sets the "release_reason" field.
func (u *PaymentBalanceHoldUpsertBulk) SetReleaseReason(v string) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetReleaseReason(v)
	})
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateReleaseReason() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateReleaseReason()
	})
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *PaymentBalanceHoldUpsertBulk) ClearReleaseReason() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.ClearReleaseReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentBalanceHoldUpsertBulk) SetUpdatedAt(v time.Time) *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentBalanceHoldUpsertBulk) UpdateUpdatedAt() *PaymentBalanceHoldUpsertBulk {
	return u.Update(func(s *PaymentBalanceHoldUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentBalanceHoldUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentBalanceHoldCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentBalanceHoldCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentBalanceHoldUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
