// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcard"
)

// RedeemCardCreate is the builder for creating a RedeemCard entity.
type RedeemCardCreate struct {
	config
	mutation *RedeemCardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetToken sets the "token" field.
func (_c *RedeemCardCreate) SetToken(v string) *RedeemCardCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCardCreate) SetRedeemCodeID(v int64) *RedeemCardCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetTheme sets the "theme" field.
func (_c *RedeemCardCreate) SetTheme(v string) *RedeemCardCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableTheme(v *string) *RedeemCardCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *RedeemCardCreate) SetContent(v map[string]interface{}) *RedeemCardCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *RedeemCardCreate) SetCreatedBy(v int64) *RedeemCardCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableCreatedBy(v *int64) *RedeemCardCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *RedeemCardCreate) SetViewCount(v int) *RedeemCardCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableViewCount(v *int) *RedeemCardCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (_c *RedeemCardCreate) SetLastViewedAt(v time.Time) *RedeemCardCreate {
	_c.mutation.SetLastViewedAt(v)
	return _c
}

// SetNillableLastViewedAt sets the "last_viewed_at" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableLastViewedAt(v *time.Time) *RedeemCardCreate {
	if v != nil {
		_c.SetLastViewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RedeemCardCreate) SetCreatedAt(v time.Time) *RedeemCardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableCreatedAt(v *time.Time) *RedeemCardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RedeemCardCreate) SetUpdatedAt(v time.Time) *RedeemCardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RedeemCardCreate) SetNillableUpdatedAt(v *time.Time) *RedeemCardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemCardMutation object of the builder.
func (_c *RedeemCardCreate) Mutation() *RedeemCardMutation {
	return _c.mutation
}

// Save creates the RedeemCard in the database.
func (_c *RedeemCardCreate) Save(ctx context.Context) (*RedeemCard, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCardCreate) SaveX(ctx context.Context) *RedeemCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCardCreate) defaults() {
	if _, ok := _c.mutation.Theme(); !ok {
		v := redeemcard.DefaultTheme
		_c.mutation.SetTheme(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := redeemcard.DefaultContent()
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := redeemcard.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := redeemcard.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := redeemcard.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCardCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "RedeemCard.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := redeemcard.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "RedeemCard.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemCard.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "RedeemCard.theme"`)}
	}
	if v, ok := _c.mutation.Theme(); ok {
		if err := redeemcard.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "RedeemCard.theme": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "RedeemCard.content"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "RedeemCard.view_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RedeemCard.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RedeemCard.updated_at"`)}
	}
	return nil
}

func (_c *RedeemCardCreate) sqlSave(ctx context.Context) (*RedeemCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCardCreate) createSpec() (*RedeemCard, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcard.Table, sqlgraph.NewFieldSpec(redeemcard.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(redeemcard.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcard.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(redeemcard.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(redeemcard.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(redeemcard.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(redeemcard.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.LastViewedAt(); ok {
		_spec.SetField(redeemcard.FieldLastViewedAt, field.TypeTime, value)
		_node.LastViewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(redeemcard.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(redeemcard.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCard.Create().
//		SetToken(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCardUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCardCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCardUpsertOne {
	_c.conflict = opts
	return &RedeemCardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCardCreate) OnConflictColumns(columns ...string) *RedeemCardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCardUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCardUpsertOne is the builder for "upsert"-ing
	//  one RedeemCard node.
	RedeemCardUpsertOne struct {
		create *RedeemCardCreate
	}

	// RedeemCardUpsert is the "OnConflict" setter.
	RedeemCardUpsert struct {
		*sql.UpdateSet
	}
)

// SetToken sets the "token" field.
func (u *RedeemCardUpsert) SetToken(v string) *RedeemCardUpsert {
	u.Set(redeemcard.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateToken() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldToken)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCardUpsert) SetRedeemCodeID(v int64) *RedeemCardUpsert {
	u.Set(redeemcard.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateRedeemCodeID() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCardUpsert) AddRedeemCodeID(v int64) *RedeemCardUpsert {
	u.Add(redeemcard.FieldRedeemCodeID, v)
	return u
}

// SetTheme sets the "theme" field.
func (u *RedeemCardUpsert) SetTheme(v string) *RedeemCardUpsert {
	u.Set(redeemcard.FieldTheme, v)
	return u
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateTheme() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldTheme)
	return u
}

// SetContent sets the "content" field.
func (u *RedeemCardUpsert) SetContent(v map[string]interface{}) *RedeemCardUpsert {
	u.Set(redeemcard.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateContent() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldContent)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCardUpsert) SetCreatedBy(v int64) *RedeemCardUpsert {
	u.Set(redeemcard.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateCreatedBy() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCardUpsert) AddCreatedBy(v int64) *RedeemCardUpsert {
	u.Add(redeemcard.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RedeemCardUpsert) ClearCreatedBy() *RedeemCardUpsert {
	u.SetNull(redeemcard.FieldCreatedBy)
	return u
}

// SetViewCount sets the "view_count" field.
func (u *RedeemCardUpsert) SetViewCount(v int) *RedeemCardUpsert {
	u.Set(redeemcard.FieldViewCount, v)
	return u
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateViewCount() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldViewCount)
	return u
}

// AddViewCount adds v to the "view_count" field.
func (u *RedeemCardUpsert) AddViewCount(v int) *RedeemCardUpsert {
	u.Add(redeemcard.FieldViewCount, v)
	return u
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *RedeemCardUpsert) SetLastViewedAt(v time.Time) *RedeemCardUpsert {
	u.Set(redeemcard.FieldLastViewedAt, v)
	return u
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateLastViewedAt() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldLastViewedAt)
	return u
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *RedeemCardUpsert) ClearLastViewedAt() *RedeemCardUpsert {
	u.SetNull(redeemcard.FieldLastViewedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemCardUpsert) SetUpdatedAt(v time.Time) *RedeemCardUpsert {
	u.Set(redeemcard.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemCardUpsert) UpdateUpdatedAt() *RedeemCardUpsert {
	u.SetExcluded(redeemcard.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCardUpsertOne) UpdateNewValues() *RedeemCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(redeemcard.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCardUpsertOne) Ignore() *RedeemCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCardUpsertOne) DoNothing() *RedeemCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCardCreate.OnConflict
// documentation for more info.
func (u *RedeemCardUpsertOne) Update(set func(*RedeemCardUpsert)) *RedeemCardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCardUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *RedeemCardUpsertOne) SetToken(v string) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateToken() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateToken()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCardUpsertOne) SetRedeemCodeID(v int64) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCardUpsertOne) AddRedeemCodeID(v int64) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateRedeemCodeID() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetTheme sets the "theme" field.
func (u *RedeemCardUpsertOne) SetTheme(v string) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetTheme(v)
	})
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateTheme() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateTheme()
	})
}

// SetContent sets the "content" field.
func (u *RedeemCardUpsertOne) SetContent(v map[string]interface{}) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateContent() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateContent()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCardUpsertOne) SetCreatedBy(v int64) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCardUpsertOne) AddCreatedBy(v int64) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateCreatedBy() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RedeemCardUpsertOne) ClearCreatedBy() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.ClearCreatedBy()
	})
}

// SetViewCount sets the "view_count" field.
func (u *RedeemCardUpsertOne) SetViewCount(v int) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *RedeemCardUpsertOne) AddViewCount(v int) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateViewCount() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateViewCount()
	})
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *RedeemCardUpsertOne) SetLastViewedAt(v time.Time) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetLastViewedAt(v)
	})
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateLastViewedAt() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateLastViewedAt()
	})
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *RedeemCardUpsertOne) ClearLastViewedAt() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.ClearLastViewedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemCardUpsertOne) SetUpdatedAt(v time.Time) *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemCardUpsertOne) UpdateUpdatedAt() *RedeemCardUpsertOne {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RedeemCardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCardCreateBulk is the builder for creating many RedeemCard entities in bulk.
type RedeemCardCreateBulk struct {
	config
	err      error
	builders []*RedeemCardCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCard entities in the database.
func (_c *RedeemCardCreateBulk) Save(ctx context.Context) ([]*RedeemCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCardCreateBulk) SaveX(ctx context.Context) []*RedeemCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCard.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCardUpsert) {
//			SetToken(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCardCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCardUpsertBulk {
	_c.conflict = opts
	return &RedeemCardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCardCreateBulk) OnConflictColumns(columns ...string) *RedeemCardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCardUpsertBulk{
		create: _c,
	}
}

// RedeemCardUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCard nodes.
type RedeemCardUpsertBulk struct {
	create *RedeemCardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCardUpsertBulk) UpdateNewValues() *RedeemCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(redeemcard.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCard.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCardUpsertBulk) Ignore() *RedeemCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCardUpsertBulk) DoNothing() *RedeemCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCardCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCardUpsertBulk) Update(set func(*RedeemCardUpsert)) *RedeemCardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCardUpsert{UpdateSet: update})
	}))
	return u
}

// SetToken sets the "token" field.
func (u *RedeemCardUpsertBulk) SetToken(v string) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateToken() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateToken()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCardUpsertBulk) SetRedeemCodeID(v int64) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCardUpsertBulk) AddRedeemCodeID(v int64) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateRedeemCodeID() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetTheme sets the "theme" field.
func (u *RedeemCardUpsertBulk) SetTheme(v string) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetTheme(v)
	})
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateTheme() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateTheme()
	})
}

// SetContent sets the "content" field.
func (u *RedeemCardUpsertBulk) SetContent(v map[string]interface{}) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateContent() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateContent()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCardUpsertBulk) SetCreatedBy(v int64) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCardUpsertBulk) AddCreatedBy(v int64) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateCreatedBy() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *RedeemCardUpsertBulk) ClearCreatedBy() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.ClearCreatedBy()
	})
}

// SetViewCount sets the "view_count" field.
func (u *RedeemCardUpsertBulk) SetViewCount(v int) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetViewCount(v)
	})
}

// AddViewCount adds v to the "view_count" field.
func (u *RedeemCardUpsertBulk) AddViewCount(v int) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.AddViewCount(v)
	})
}

// UpdateViewCount sets the "view_count" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateViewCount() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateViewCount()
	})
}

// SetLastViewedAt sets the "last_viewed_at" field.
func (u *RedeemCardUpsertBulk) SetLastViewedAt(v time.Time) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetLastViewedAt(v)
	})
}

// UpdateLastViewedAt sets the "last_viewed_at" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateLastViewedAt() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateLastViewedAt()
	})
}

// ClearLastViewedAt clears the value of the "last_viewed_at" field.
func (u *RedeemCardUpsertBulk) ClearLastViewedAt() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.ClearLastViewedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemCardUpsertBulk) SetUpdatedAt(v time.Time) *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemCardUpsertBulk) UpdateUpdatedAt() *RedeemCardUpsertBulk {
	return u.Update(func(s *RedeemCardUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RedeemCardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
