// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reimbursementrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReimbursementRequestUpdate is the builder for updating ReimbursementRequest entities.
type ReimbursementRequestUpdate struct {
	config
	hooks    []Hook
	mutation *ReimbursementRequestMutation
}

// Where appends a list predicates to the ReimbursementRequestUpdate builder.
func (_u *ReimbursementRequestUpdate) Where(ps ...predicate.ReimbursementRequest) *ReimbursementRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReimbursementRequestUpdate) SetUserID(v int64) *ReimbursementRequestUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableUserID(v *int64) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRawText sets the "raw_text" field.
func (_u *ReimbursementRequestUpdate) SetRawText(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetRawText(v)
	return _u
}

// SetNillableRawText sets the "raw_text" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableRawText(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetRawText(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *ReimbursementRequestUpdate) SetCompanyName(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableCompanyName(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *ReimbursementRequestUpdate) SetTaxID(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableTaxID(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *ReimbursementRequestUpdate) SetBankAccount(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableBankAccount(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *ReimbursementRequestUpdate) SetBankName(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableBankName(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *ReimbursementRequestUpdate) SetAddress(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableAddress(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReimbursementRequestUpdate) SetAmount(v float64) *ReimbursementRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableAmount(v *float64) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReimbursementRequestUpdate) AddAmount(v float64) *ReimbursementRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReimbursementRequestUpdate) SetStatus(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableStatus(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPdfPath sets the "pdf_path" field.
func (_u *ReimbursementRequestUpdate) SetPdfPath(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetPdfPath(v)
	return _u
}

// SetNillablePdfPath sets the "pdf_path" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillablePdfPath(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetPdfPath(*v)
	}
	return _u
}

// SetPdfFileName sets the "pdf_file_name" field.
func (_u *ReimbursementRequestUpdate) SetPdfFileName(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetPdfFileName(v)
	return _u
}

// SetNillablePdfFileName sets the "pdf_file_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillablePdfFileName(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetPdfFileName(*v)
	}
	return _u
}

// SetPdfSize sets the "pdf_size" field.
func (_u *ReimbursementRequestUpdate) SetPdfSize(v int64) *ReimbursementRequestUpdate {
	_u.mutation.ResetPdfSize()
	_u.mutation.SetPdfSize(v)
	return _u
}

// SetNillablePdfSize sets the "pdf_size" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillablePdfSize(v *int64) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetPdfSize(*v)
	}
	return _u
}

// AddPdfSize adds value to the "pdf_size" field.
func (_u *ReimbursementRequestUpdate) AddPdfSize(v int64) *ReimbursementRequestUpdate {
	_u.mutation.AddPdfSize(v)
	return _u
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (_u *ReimbursementRequestUpdate) SetPdfSha256(v string) *ReimbursementRequestUpdate {
	_u.mutation.SetPdfSha256(v)
	return _u
}

// SetNillablePdfSha256 sets the "pdf_sha256" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillablePdfSha256(v *string) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetPdfSha256(*v)
	}
	return _u
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (_u *ReimbursementRequestUpdate) SetPdfUploadedAt(v time.Time) *ReimbursementRequestUpdate {
	_u.mutation.SetPdfUploadedAt(v)
	return _u
}

// SetNillablePdfUploadedAt sets the "pdf_uploaded_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillablePdfUploadedAt(v *time.Time) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetPdfUploadedAt(*v)
	}
	return _u
}

// ClearPdfUploadedAt clears the value of the "pdf_uploaded_at" field.
func (_u *ReimbursementRequestUpdate) ClearPdfUploadedAt() *ReimbursementRequestUpdate {
	_u.mutation.ClearPdfUploadedAt()
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *ReimbursementRequestUpdate) SetHandledBy(v int64) *ReimbursementRequestUpdate {
	_u.mutation.ResetHandledBy()
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableHandledBy(v *int64) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// AddHandledBy adds value to the "handled_by" field.
func (_u *ReimbursementRequestUpdate) AddHandledBy(v int64) *ReimbursementRequestUpdate {
	_u.mutation.AddHandledBy(v)
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *ReimbursementRequestUpdate) ClearHandledBy() *ReimbursementRequestUpdate {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ReimbursementRequestUpdate) SetCompletedAt(v time.Time) *ReimbursementRequestUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableCompletedAt(v *time.Time) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ReimbursementRequestUpdate) ClearCompletedAt() *ReimbursementRequestUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *ReimbursementRequestUpdate) SetNotifiedAt(v time.Time) *ReimbursementRequestUpdate {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdate) SetNillableNotifiedAt(v *time.Time) *ReimbursementRequestUpdate {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *ReimbursementRequestUpdate) ClearNotifiedAt() *ReimbursementRequestUpdate {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReimbursementRequestUpdate) SetUpdatedAt(v time.Time) *ReimbursementRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReimbursementRequestUpdate) SetUser(v *User) *ReimbursementRequestUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ReimbursementRequestMutation object of the builder.
func (_u *ReimbursementRequestUpdate) Mutation() *ReimbursementRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReimbursementRequestUpdate) ClearUser() *ReimbursementRequestUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReimbursementRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReimbursementRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReimbursementRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReimbursementRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReimbursementRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reimbursementrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReimbursementRequestUpdate) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := reimbursementrequest.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := reimbursementrequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := reimbursementrequest.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := reimbursementrequest.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := reimbursementrequest.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reimbursementrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfPath(); ok {
		if err := reimbursementrequest.PdfPathValidator(v); err != nil {
			return &ValidationError{Name: "pdf_path", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfFileName(); ok {
		if err := reimbursementrequest.PdfFileNameValidator(v); err != nil {
			return &ValidationError{Name: "pdf_file_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfSha256(); ok {
		if err := reimbursementrequest.PdfSha256Validator(v); err != nil {
			return &ValidationError{Name: "pdf_sha256", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_sha256": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReimbursementRequest.user"`)
	}
	return nil
}

func (_u *ReimbursementRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reimbursementrequest.Table, reimbursementrequest.Columns, sqlgraph.NewFieldSpec(reimbursementrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RawText(); ok {
		_spec.SetField(reimbursementrequest.FieldRawText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(reimbursementrequest.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(reimbursementrequest.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(reimbursementrequest.FieldBankAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(reimbursementrequest.FieldBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(reimbursementrequest.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(reimbursementrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(reimbursementrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reimbursementrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfPath(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfFileName(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfSize(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPdfSize(); ok {
		_spec.AddField(reimbursementrequest.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PdfSha256(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfUploadedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.PdfUploadedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldPdfUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(reimbursementrequest.FieldHandledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHandledBy(); ok {
		_spec.AddField(reimbursementrequest.FieldHandledBy, field.TypeInt64, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(reimbursementrequest.FieldHandledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reimbursementrequest.UserTable,
			Columns: []string{reimbursementrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reimbursementrequest.UserTable,
			Columns: []string{reimbursementrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reimbursementrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReimbursementRequestUpdateOne is the builder for updating a single ReimbursementRequest entity.
type ReimbursementRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReimbursementRequestMutation
}

// SetUserID sets the "user_id" field.
func (_u *ReimbursementRequestUpdateOne) SetUserID(v int64) *ReimbursementRequestUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableUserID(v *int64) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRawText sets the "raw_text" field.
func (_u *ReimbursementRequestUpdateOne) SetRawText(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetRawText(v)
	return _u
}

// SetNillableRawText sets the "raw_text" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableRawText(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetRawText(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *ReimbursementRequestUpdateOne) SetCompanyName(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableCompanyName(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *ReimbursementRequestUpdateOne) SetTaxID(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableTaxID(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *ReimbursementRequestUpdateOne) SetBankAccount(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableBankAccount(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *ReimbursementRequestUpdateOne) SetBankName(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableBankName(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *ReimbursementRequestUpdateOne) SetAddress(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableAddress(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReimbursementRequestUpdateOne) SetAmount(v float64) *ReimbursementRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableAmount(v *float64) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReimbursementRequestUpdateOne) AddAmount(v float64) *ReimbursementRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReimbursementRequestUpdateOne) SetStatus(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableStatus(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPdfPath sets the "pdf_path" field.
func (_u *ReimbursementRequestUpdateOne) SetPdfPath(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetPdfPath(v)
	return _u
}

// SetNillablePdfPath sets the "pdf_path" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillablePdfPath(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetPdfPath(*v)
	}
	return _u
}

// SetPdfFileName sets the "pdf_file_name" field.
func (_u *ReimbursementRequestUpdateOne) SetPdfFileName(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetPdfFileName(v)
	return _u
}

// SetNillablePdfFileName sets the "pdf_file_name" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillablePdfFileName(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetPdfFileName(*v)
	}
	return _u
}

// SetPdfSize sets the "pdf_size" field.
func (_u *ReimbursementRequestUpdateOne) SetPdfSize(v int64) *ReimbursementRequestUpdateOne {
	_u.mutation.ResetPdfSize()
	_u.mutation.SetPdfSize(v)
	return _u
}

// SetNillablePdfSize sets the "pdf_size" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillablePdfSize(v *int64) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetPdfSize(*v)
	}
	return _u
}

// AddPdfSize adds value to the "pdf_size" field.
func (_u *ReimbursementRequestUpdateOne) AddPdfSize(v int64) *ReimbursementRequestUpdateOne {
	_u.mutation.AddPdfSize(v)
	return _u
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (_u *ReimbursementRequestUpdateOne) SetPdfSha256(v string) *ReimbursementRequestUpdateOne {
	_u.mutation.SetPdfSha256(v)
	return _u
}

// SetNillablePdfSha256 sets the "pdf_sha256" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillablePdfSha256(v *string) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetPdfSha256(*v)
	}
	return _u
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (_u *ReimbursementRequestUpdateOne) SetPdfUploadedAt(v time.Time) *ReimbursementRequestUpdateOne {
	_u.mutation.SetPdfUploadedAt(v)
	return _u
}

// SetNillablePdfUploadedAt sets the "pdf_uploaded_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillablePdfUploadedAt(v *time.Time) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetPdfUploadedAt(*v)
	}
	return _u
}

// ClearPdfUploadedAt clears the value of the "pdf_uploaded_at" field.
func (_u *ReimbursementRequestUpdateOne) ClearPdfUploadedAt() *ReimbursementRequestUpdateOne {
	_u.mutation.ClearPdfUploadedAt()
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *ReimbursementRequestUpdateOne) SetHandledBy(v int64) *ReimbursementRequestUpdateOne {
	_u.mutation.ResetHandledBy()
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableHandledBy(v *int64) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// AddHandledBy adds value to the "handled_by" field.
func (_u *ReimbursementRequestUpdateOne) AddHandledBy(v int64) *ReimbursementRequestUpdateOne {
	_u.mutation.AddHandledBy(v)
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *ReimbursementRequestUpdateOne) ClearHandledBy() *ReimbursementRequestUpdateOne {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ReimbursementRequestUpdateOne) SetCompletedAt(v time.Time) *ReimbursementRequestUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableCompletedAt(v *time.Time) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ReimbursementRequestUpdateOne) ClearCompletedAt() *ReimbursementRequestUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *ReimbursementRequestUpdateOne) SetNotifiedAt(v time.Time) *ReimbursementRequestUpdateOne {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *ReimbursementRequestUpdateOne) SetNillableNotifiedAt(v *time.Time) *ReimbursementRequestUpdateOne {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *ReimbursementRequestUpdateOne) ClearNotifiedAt() *ReimbursementRequestUpdateOne {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReimbursementRequestUpdateOne) SetUpdatedAt(v time.Time) *ReimbursementRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ReimbursementRequestUpdateOne) SetUser(v *User) *ReimbursementRequestUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ReimbursementRequestMutation object of the builder.
func (_u *ReimbursementRequestUpdateOne) Mutation() *ReimbursementRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ReimbursementRequestUpdateOne) ClearUser() *ReimbursementRequestUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ReimbursementRequestUpdate builder.
func (_u *ReimbursementRequestUpdateOne) Where(ps ...predicate.ReimbursementRequest) *ReimbursementRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReimbursementRequestUpdateOne) Select(field string, fields ...string) *ReimbursementRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReimbursementRequest entity.
func (_u *ReimbursementRequestUpdateOne) Save(ctx context.Context) (*ReimbursementRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReimbursementRequestUpdateOne) SaveX(ctx context.Context) *ReimbursementRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReimbursementRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReimbursementRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReimbursementRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reimbursementrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReimbursementRequestUpdateOne) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := reimbursementrequest.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := reimbursementrequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := reimbursementrequest.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := reimbursementrequest.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := reimbursementrequest.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reimbursementrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfPath(); ok {
		if err := reimbursementrequest.PdfPathValidator(v); err != nil {
			return &ValidationError{Name: "pdf_path", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfFileName(); ok {
		if err := reimbursementrequest.PdfFileNameValidator(v); err != nil {
			return &ValidationError{Name: "pdf_file_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PdfSha256(); ok {
		if err := reimbursementrequest.PdfSha256Validator(v); err != nil {
			return &ValidationError{Name: "pdf_sha256", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_sha256": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReimbursementRequest.user"`)
	}
	return nil
}

func (_u *ReimbursementRequestUpdateOne) sqlSave(ctx context.Context) (_node *ReimbursementRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reimbursementrequest.Table, reimbursementrequest.Columns, sqlgraph.NewFieldSpec(reimbursementrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReimbursementRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reimbursementrequest.FieldID)
		for _, f := range fields {
			if !reimbursementrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reimbursementrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RawText(); ok {
		_spec.SetField(reimbursementrequest.FieldRawText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(reimbursementrequest.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(reimbursementrequest.FieldTaxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(reimbursementrequest.FieldBankAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(reimbursementrequest.FieldBankName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(reimbursementrequest.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(reimbursementrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(reimbursementrequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reimbursementrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfPath(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfFileName(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfSize(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPdfSize(); ok {
		_spec.AddField(reimbursementrequest.FieldPdfSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PdfSha256(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.PdfUploadedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.PdfUploadedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldPdfUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(reimbursementrequest.FieldHandledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHandledBy(); ok {
		_spec.AddField(reimbursementrequest.FieldHandledBy, field.TypeInt64, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(reimbursementrequest.FieldHandledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(reimbursementrequest.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reimbursementrequest.UserTable,
			Columns: []string{reimbursementrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reimbursementrequest.UserTable,
			Columns: []string{reimbursementrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReimbursementRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reimbursementrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
