// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/reimbursementrequest"
)

// ReimbursementRequestDelete is the builder for deleting a ReimbursementRequest entity.
type ReimbursementRequestDelete struct {
	config
	hooks    []Hook
	mutation *ReimbursementRequestMutation
}

// Where appends a list predicates to the ReimbursementRequestDelete builder.
func (_d *ReimbursementRequestDelete) Where(ps ...predicate.ReimbursementRequest) *ReimbursementRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReimbursementRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReimbursementRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReimbursementRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reimbursementrequest.Table, sqlgraph.NewFieldSpec(reimbursementrequest.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReimbursementRequestDeleteOne is the builder for deleting a single ReimbursementRequest entity.
type ReimbursementRequestDeleteOne struct {
	_d *ReimbursementRequestDelete
}

// Where appends a list predicates to the ReimbursementRequestDelete builder.
func (_d *ReimbursementRequestDeleteOne) Where(ps ...predicate.ReimbursementRequest) *ReimbursementRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReimbursementRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reimbursementrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReimbursementRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
