// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/reimbursementrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReimbursementRequest is the model entity for the ReimbursementRequest schema.
type ReimbursementRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RawText holds the value of the "raw_text" field.
	RawText string `json:"raw_text,omitempty"`
	// CompanyName holds the value of the "company_name" field.
	CompanyName string `json:"company_name,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID string `json:"tax_id,omitempty"`
	// BankAccount holds the value of the "bank_account" field.
	BankAccount string `json:"bank_account,omitempty"`
	// BankName holds the value of the "bank_name" field.
	BankName string `json:"bank_name,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PdfPath holds the value of the "pdf_path" field.
	PdfPath string `json:"pdf_path,omitempty"`
	// PdfFileName holds the value of the "pdf_file_name" field.
	PdfFileName string `json:"pdf_file_name,omitempty"`
	// PdfSize holds the value of the "pdf_size" field.
	PdfSize int64 `json:"pdf_size,omitempty"`
	// PdfSha256 holds the value of the "pdf_sha256" field.
	PdfSha256 string `json:"pdf_sha256,omitempty"`
	// PdfUploadedAt holds the value of the "pdf_uploaded_at" field.
	PdfUploadedAt *time.Time `json:"pdf_uploaded_at,omitempty"`
	// HandledBy holds the value of the "handled_by" field.
	HandledBy *int64 `json:"handled_by,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// NotifiedAt holds the value of the "notified_at" field.
	NotifiedAt *time.Time `json:"notified_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReimbursementRequestQuery when eager-loading is set.
	Edges        ReimbursementRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReimbursementRequestEdges holds the relations/edges for other nodes in the graph.
type ReimbursementRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReimbursementRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReimbursementRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reimbursementrequest.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case reimbursementrequest.FieldID, reimbursementrequest.FieldUserID, reimbursementrequest.FieldPdfSize, reimbursementrequest.FieldHandledBy:
			values[i] = new(sql.NullInt64)
		case reimbursementrequest.FieldRawText, reimbursementrequest.FieldCompanyName, reimbursementrequest.FieldTaxID, reimbursementrequest.FieldBankAccount, reimbursementrequest.FieldBankName, reimbursementrequest.FieldAddress, reimbursementrequest.FieldStatus, reimbursementrequest.FieldPdfPath, reimbursementrequest.FieldPdfFileName, reimbursementrequest.FieldPdfSha256:
			values[i] = new(sql.NullString)
		case reimbursementrequest.FieldPdfUploadedAt, reimbursementrequest.FieldCompletedAt, reimbursementrequest.FieldNotifiedAt, reimbursementrequest.FieldCreatedAt, reimbursementrequest.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReimbursementRequest fields.
func (_m *ReimbursementRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reimbursementrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case reimbursementrequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case reimbursementrequest.FieldRawText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_text", values[i])
			} else if value.Valid {
				_m.RawText = value.String
			}
		case reimbursementrequest.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case reimbursementrequest.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = value.String
			}
		case reimbursementrequest.FieldBankAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bank_account", values[i])
			} else if value.Valid {
				_m.BankAccount = value.String
			}
		case reimbursementrequest.FieldBankName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bank_name", values[i])
			} else if value.Valid {
				_m.BankName = value.String
			}
		case reimbursementrequest.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case reimbursementrequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case reimbursementrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case reimbursementrequest.FieldPdfPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_path", values[i])
			} else if value.Valid {
				_m.PdfPath = value.String
			}
		case reimbursementrequest.FieldPdfFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_file_name", values[i])
			} else if value.Valid {
				_m.PdfFileName = value.String
			}
		case reimbursementrequest.FieldPdfSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_size", values[i])
			} else if value.Valid {
				_m.PdfSize = value.Int64
			}
		case reimbursementrequest.FieldPdfSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_sha256", values[i])
			} else if value.Valid {
				_m.PdfSha256 = value.String
			}
		case reimbursementrequest.FieldPdfUploadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field pdf_uploaded_at", values[i])
			} else if value.Valid {
				_m.PdfUploadedAt = new(time.Time)
				*_m.PdfUploadedAt = value.Time
			}
		case reimbursementrequest.FieldHandledBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field handled_by", values[i])
			} else if value.Valid {
				_m.HandledBy = new(int64)
				*_m.HandledBy = value.Int64
			}
		case reimbursementrequest.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case reimbursementrequest.FieldNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field notified_at", values[i])
			} else if value.Valid {
				_m.NotifiedAt = new(time.Time)
				*_m.NotifiedAt = value.Time
			}
		case reimbursementrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reimbursementrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReimbursementRequest.
// This includes values selected through modifiers, order, etc.
func (_m *ReimbursementRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ReimbursementRequest entity.
func (_m *ReimbursementRequest) QueryUser() *UserQuery {
	return NewReimbursementRequestClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ReimbursementRequest.
// Note that you need to call ReimbursementRequest.Unwrap() before calling this method if this ReimbursementRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReimbursementRequest) Update() *ReimbursementRequestUpdateOne {
	return NewReimbursementRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReimbursementRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReimbursementRequest) Unwrap() *ReimbursementRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReimbursementRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReimbursementRequest) String() string {
	var builder strings.Builder
	builder.WriteString("ReimbursementRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("raw_text=")
	builder.WriteString(_m.RawText)
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("tax_id=")
	builder.WriteString(_m.TaxID)
	builder.WriteString(", ")
	builder.WriteString("bank_account=")
	builder.WriteString(_m.BankAccount)
	builder.WriteString(", ")
	builder.WriteString("bank_name=")
	builder.WriteString(_m.BankName)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("pdf_path=")
	builder.WriteString(_m.PdfPath)
	builder.WriteString(", ")
	builder.WriteString("pdf_file_name=")
	builder.WriteString(_m.PdfFileName)
	builder.WriteString(", ")
	builder.WriteString("pdf_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.PdfSize))
	builder.WriteString(", ")
	builder.WriteString("pdf_sha256=")
	builder.WriteString(_m.PdfSha256)
	builder.WriteString(", ")
	if v := _m.PdfUploadedAt; v != nil {
		builder.WriteString("pdf_uploaded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.HandledBy; v != nil {
		builder.WriteString("handled_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NotifiedAt; v != nil {
		builder.WriteString("notified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReimbursementRequests is a parsable slice of ReimbursementRequest.
type ReimbursementRequests []*ReimbursementRequest
