// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/reimbursementrequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReimbursementRequestCreate is the builder for creating a ReimbursementRequest entity.
type ReimbursementRequestCreate struct {
	config
	mutation *ReimbursementRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ReimbursementRequestCreate) SetUserID(v int64) *ReimbursementRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRawText sets the "raw_text" field.
func (_c *ReimbursementRequestCreate) SetRawText(v string) *ReimbursementRequestCreate {
	_c.mutation.SetRawText(v)
	return _c
}

// SetNillableRawText sets the "raw_text" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableRawText(v *string) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetRawText(*v)
	}
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *ReimbursementRequestCreate) SetCompanyName(v string) *ReimbursementRequestCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *ReimbursementRequestCreate) SetTaxID(v string) *ReimbursementRequestCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetBankAccount sets the "bank_account" field.
func (_c *ReimbursementRequestCreate) SetBankAccount(v string) *ReimbursementRequestCreate {
	_c.mutation.SetBankAccount(v)
	return _c
}

// SetBankName sets the "bank_name" field.
func (_c *ReimbursementRequestCreate) SetBankName(v string) *ReimbursementRequestCreate {
	_c.mutation.SetBankName(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *ReimbursementRequestCreate) SetAddress(v string) *ReimbursementRequestCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ReimbursementRequestCreate) SetAmount(v float64) *ReimbursementRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReimbursementRequestCreate) SetStatus(v string) *ReimbursementRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableStatus(v *string) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPdfPath sets the "pdf_path" field.
func (_c *ReimbursementRequestCreate) SetPdfPath(v string) *ReimbursementRequestCreate {
	_c.mutation.SetPdfPath(v)
	return _c
}

// SetNillablePdfPath sets the "pdf_path" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillablePdfPath(v *string) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetPdfPath(*v)
	}
	return _c
}

// SetPdfFileName sets the "pdf_file_name" field.
func (_c *ReimbursementRequestCreate) SetPdfFileName(v string) *ReimbursementRequestCreate {
	_c.mutation.SetPdfFileName(v)
	return _c
}

// SetNillablePdfFileName sets the "pdf_file_name" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillablePdfFileName(v *string) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetPdfFileName(*v)
	}
	return _c
}

// SetPdfSize sets the "pdf_size" field.
func (_c *ReimbursementRequestCreate) SetPdfSize(v int64) *ReimbursementRequestCreate {
	_c.mutation.SetPdfSize(v)
	return _c
}

// SetNillablePdfSize sets the "pdf_size" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillablePdfSize(v *int64) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetPdfSize(*v)
	}
	return _c
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (_c *ReimbursementRequestCreate) SetPdfSha256(v string) *ReimbursementRequestCreate {
	_c.mutation.SetPdfSha256(v)
	return _c
}

// SetNillablePdfSha256 sets the "pdf_sha256" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillablePdfSha256(v *string) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetPdfSha256(*v)
	}
	return _c
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (_c *ReimbursementRequestCreate) SetPdfUploadedAt(v time.Time) *ReimbursementRequestCreate {
	_c.mutation.SetPdfUploadedAt(v)
	return _c
}

// SetNillablePdfUploadedAt sets the "pdf_uploaded_at" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillablePdfUploadedAt(v *time.Time) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetPdfUploadedAt(*v)
	}
	return _c
}

// SetHandledBy sets the "handled_by" field.
func (_c *ReimbursementRequestCreate) SetHandledBy(v int64) *ReimbursementRequestCreate {
	_c.mutation.SetHandledBy(v)
	return _c
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableHandledBy(v *int64) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetHandledBy(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ReimbursementRequestCreate) SetCompletedAt(v time.Time) *ReimbursementRequestCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableCompletedAt(v *time.Time) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *ReimbursementRequestCreate) SetNotifiedAt(v time.Time) *ReimbursementRequestCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableNotifiedAt(v *time.Time) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReimbursementRequestCreate) SetCreatedAt(v time.Time) *ReimbursementRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableCreatedAt(v *time.Time) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReimbursementRequestCreate) SetUpdatedAt(v time.Time) *ReimbursementRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReimbursementRequestCreate) SetNillableUpdatedAt(v *time.Time) *ReimbursementRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ReimbursementRequestCreate) SetUser(v *User) *ReimbursementRequestCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ReimbursementRequestMutation object of the builder.
func (_c *ReimbursementRequestCreate) Mutation() *ReimbursementRequestMutation {
	return _c.mutation
}

// Save creates the ReimbursementRequest in the database.
func (_c *ReimbursementRequestCreate) Save(ctx context.Context) (*ReimbursementRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReimbursementRequestCreate) SaveX(ctx context.Context) *ReimbursementRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReimbursementRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReimbursementRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReimbursementRequestCreate) defaults() {
	if _, ok := _c.mutation.RawText(); !ok {
		v := reimbursementrequest.DefaultRawText
		_c.mutation.SetRawText(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := reimbursementrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PdfPath(); !ok {
		v := reimbursementrequest.DefaultPdfPath
		_c.mutation.SetPdfPath(v)
	}
	if _, ok := _c.mutation.PdfFileName(); !ok {
		v := reimbursementrequest.DefaultPdfFileName
		_c.mutation.SetPdfFileName(v)
	}
	if _, ok := _c.mutation.PdfSize(); !ok {
		v := reimbursementrequest.DefaultPdfSize
		_c.mutation.SetPdfSize(v)
	}
	if _, ok := _c.mutation.PdfSha256(); !ok {
		v := reimbursementrequest.DefaultPdfSha256
		_c.mutation.SetPdfSha256(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reimbursementrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := reimbursementrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReimbursementRequestCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ReimbursementRequest.user_id"`)}
	}
	if _, ok := _c.mutation.RawText(); !ok {
		return &ValidationError{Name: "raw_text", err: errors.New(`ent: missing required field "ReimbursementRequest.raw_text"`)}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "ReimbursementRequest.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := reimbursementrequest.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxID(); !ok {
		return &ValidationError{Name: "tax_id", err: errors.New(`ent: missing required field "ReimbursementRequest.tax_id"`)}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := reimbursementrequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.tax_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BankAccount(); !ok {
		return &ValidationError{Name: "bank_account", err: errors.New(`ent: missing required field "ReimbursementRequest.bank_account"`)}
	}
	if v, ok := _c.mutation.BankAccount(); ok {
		if err := reimbursementrequest.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BankName(); !ok {
		return &ValidationError{Name: "bank_name", err: errors.New(`ent: missing required field "ReimbursementRequest.bank_name"`)}
	}
	if v, ok := _c.mutation.BankName(); ok {
		if err := reimbursementrequest.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.bank_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "ReimbursementRequest.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := reimbursementrequest.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReimbursementRequest.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReimbursementRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := reimbursementrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PdfPath(); !ok {
		return &ValidationError{Name: "pdf_path", err: errors.New(`ent: missing required field "ReimbursementRequest.pdf_path"`)}
	}
	if v, ok := _c.mutation.PdfPath(); ok {
		if err := reimbursementrequest.PdfPathValidator(v); err != nil {
			return &ValidationError{Name: "pdf_path", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PdfFileName(); !ok {
		return &ValidationError{Name: "pdf_file_name", err: errors.New(`ent: missing required field "ReimbursementRequest.pdf_file_name"`)}
	}
	if v, ok := _c.mutation.PdfFileName(); ok {
		if err := reimbursementrequest.PdfFileNameValidator(v); err != nil {
			return &ValidationError{Name: "pdf_file_name", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PdfSize(); !ok {
		return &ValidationError{Name: "pdf_size", err: errors.New(`ent: missing required field "ReimbursementRequest.pdf_size"`)}
	}
	if _, ok := _c.mutation.PdfSha256(); !ok {
		return &ValidationError{Name: "pdf_sha256", err: errors.New(`ent: missing required field "ReimbursementRequest.pdf_sha256"`)}
	}
	if v, ok := _c.mutation.PdfSha256(); ok {
		if err := reimbursementrequest.PdfSha256Validator(v); err != nil {
			return &ValidationError{Name: "pdf_sha256", err: fmt.Errorf(`ent: validator failed for field "ReimbursementRequest.pdf_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReimbursementRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReimbursementRequest.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ReimbursementRequest.user"`)}
	}
	return nil
}

func (_c *ReimbursementRequestCreate) sqlSave(ctx context.Context) (*ReimbursementRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReimbursementRequestCreate) createSpec() (*ReimbursementRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &ReimbursementRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reimbursementrequest.Table, sqlgraph.NewFieldSpec(reimbursementrequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RawText(); ok {
		_spec.SetField(reimbursementrequest.FieldRawText, field.TypeString, value)
		_node.RawText = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(reimbursementrequest.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(reimbursementrequest.FieldTaxID, field.TypeString, value)
		_node.TaxID = value
	}
	if value, ok := _c.mutation.BankAccount(); ok {
		_spec.SetField(reimbursementrequest.FieldBankAccount, field.TypeString, value)
		_node.BankAccount = value
	}
	if value, ok := _c.mutation.BankName(); ok {
		_spec.SetField(reimbursementrequest.FieldBankName, field.TypeString, value)
		_node.BankName = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(reimbursementrequest.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(reimbursementrequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(reimbursementrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PdfPath(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfPath, field.TypeString, value)
		_node.PdfPath = value
	}
	if value, ok := _c.mutation.PdfFileName(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfFileName, field.TypeString, value)
		_node.PdfFileName = value
	}
	if value, ok := _c.mutation.PdfSize(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSize, field.TypeInt64, value)
		_node.PdfSize = value
	}
	if value, ok := _c.mutation.PdfSha256(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfSha256, field.TypeString, value)
		_node.PdfSha256 = value
	}
	if value, ok := _c.mutation.PdfUploadedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldPdfUploadedAt, field.TypeTime, value)
		_node.PdfUploadedAt = &value
	}
	if value, ok := _c.mutation.HandledBy(); ok {
		_spec.SetField(reimbursementrequest.FieldHandledBy, field.TypeInt64, value)
		_node.HandledBy = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(reimbursementrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reimbursementrequest.UserTable,
			Columns: []string{reimbursementrequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReimbursementRequest.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReimbursementRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReimbursementRequestCreate) OnConflict(opts ...sql.ConflictOption) *ReimbursementRequestUpsertOne {
	_c.conflict = opts
	return &ReimbursementRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReimbursementRequestCreate) OnConflictColumns(columns ...string) *ReimbursementRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReimbursementRequestUpsertOne{
		create: _c,
	}
}

type (
	// ReimbursementRequestUpsertOne is the builder for "upsert"-ing
	//  one ReimbursementRequest node.
	ReimbursementRequestUpsertOne struct {
		create *ReimbursementRequestCreate
	}

	// ReimbursementRequestUpsert is the "OnConflict" setter.
	ReimbursementRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ReimbursementRequestUpsert) SetUserID(v int64) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateUserID() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldUserID)
	return u
}

// SetRawText sets the "raw_text" field.
func (u *ReimbursementRequestUpsert) SetRawText(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldRawText, v)
	return u
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateRawText() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldRawText)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *ReimbursementRequestUpsert) SetCompanyName(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateCompanyName() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldCompanyName)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *ReimbursementRequestUpsert) SetTaxID(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateTaxID() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldTaxID)
	return u
}

// SetBankAccount sets the "bank_account" field.
func (u *ReimbursementRequestUpsert) SetBankAccount(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldBankAccount, v)
	return u
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateBankAccount() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldBankAccount)
	return u
}

// SetBankName sets the "bank_name" field.
func (u *ReimbursementRequestUpsert) SetBankName(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldBankName, v)
	return u
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateBankName() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldBankName)
	return u
}

// SetAddress sets the "address" field.
func (u *ReimbursementRequestUpsert) SetAddress(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateAddress() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldAddress)
	return u
}

// SetAmount sets the "amount" field.
func (u *ReimbursementRequestUpsert) SetAmount(v float64) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateAmount() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ReimbursementRequestUpsert) AddAmount(v float64) *ReimbursementRequestUpsert {
	u.Add(reimbursementrequest.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ReimbursementRequestUpsert) SetStatus(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateStatus() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldStatus)
	return u
}

// SetPdfPath sets the "pdf_path" field.
func (u *ReimbursementRequestUpsert) SetPdfPath(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldPdfPath, v)
	return u
}

// UpdatePdfPath sets the "pdf_path" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdatePdfPath() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldPdfPath)
	return u
}

// SetPdfFileName sets the "pdf_file_name" field.
func (u *ReimbursementRequestUpsert) SetPdfFileName(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldPdfFileName, v)
	return u
}

// UpdatePdfFileName sets the "pdf_file_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdatePdfFileName() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldPdfFileName)
	return u
}

// SetPdfSize sets the "pdf_size" field.
func (u *ReimbursementRequestUpsert) SetPdfSize(v int64) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldPdfSize, v)
	return u
}

// UpdatePdfSize sets the "pdf_size" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdatePdfSize() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldPdfSize)
	return u
}

// AddPdfSize adds v to the "pdf_size" field.
func (u *ReimbursementRequestUpsert) AddPdfSize(v int64) *ReimbursementRequestUpsert {
	u.Add(reimbursementrequest.FieldPdfSize, v)
	return u
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (u *ReimbursementRequestUpsert) SetPdfSha256(v string) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldPdfSha256, v)
	return u
}

// UpdatePdfSha256 sets the "pdf_sha256" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdatePdfSha256() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldPdfSha256)
	return u
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsert) SetPdfUploadedAt(v time.Time) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldPdfUploadedAt, v)
	return u
}

// UpdatePdfUploadedAt sets the "pdf_uploaded_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdatePdfUploadedAt() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldPdfUploadedAt)
	return u
}

// ClearPdfUploadedAt clears the value of the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsert) ClearPdfUploadedAt() *ReimbursementRequestUpsert {
	u.SetNull(reimbursementrequest.FieldPdfUploadedAt)
	return u
}

// SetHandledBy sets the "handled_by" field.
func (u *ReimbursementRequestUpsert) SetHandledBy(v int64) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldHandledBy, v)
	return u
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateHandledBy() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldHandledBy)
	return u
}

// AddHandledBy adds v to the "handled_by" field.
func (u *ReimbursementRequestUpsert) AddHandledBy(v int64) *ReimbursementRequestUpsert {
	u.Add(reimbursementrequest.FieldHandledBy, v)
	return u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *ReimbursementRequestUpsert) ClearHandledBy() *ReimbursementRequestUpsert {
	u.SetNull(reimbursementrequest.FieldHandledBy)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReimbursementRequestUpsert) SetCompletedAt(v time.Time) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateCompletedAt() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReimbursementRequestUpsert) ClearCompletedAt() *ReimbursementRequestUpsert {
	u.SetNull(reimbursementrequest.FieldCompletedAt)
	return u
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ReimbursementRequestUpsert) SetNotifiedAt(v time.Time) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldNotifiedAt, v)
	return u
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateNotifiedAt() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldNotifiedAt)
	return u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ReimbursementRequestUpsert) ClearNotifiedAt() *ReimbursementRequestUpsert {
	u.SetNull(reimbursementrequest.FieldNotifiedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReimbursementRequestUpsert) SetUpdatedAt(v time.Time) *ReimbursementRequestUpsert {
	u.Set(reimbursementrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsert) UpdateUpdatedAt() *ReimbursementRequestUpsert {
	u.SetExcluded(reimbursementrequest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReimbursementRequestUpsertOne) UpdateNewValues() *ReimbursementRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reimbursementrequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReimbursementRequestUpsertOne) Ignore() *ReimbursementRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReimbursementRequestUpsertOne) DoNothing() *ReimbursementRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReimbursementRequestCreate.OnConflict
// documentation for more info.
func (u *ReimbursementRequestUpsertOne) Update(set func(*ReimbursementRequestUpsert)) *ReimbursementRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReimbursementRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReimbursementRequestUpsertOne) SetUserID(v int64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateUserID() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetRawText sets the "raw_text" field.
func (u *ReimbursementRequestUpsertOne) SetRawText(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetRawText(v)
	})
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateRawText() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateRawText()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *ReimbursementRequestUpsertOne) SetCompanyName(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateCompanyName() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateCompanyName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *ReimbursementRequestUpsertOne) SetTaxID(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateTaxID() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateTaxID()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *ReimbursementRequestUpsertOne) SetBankAccount(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateBankAccount() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// SetBankName sets the "bank_name" field.
func (u *ReimbursementRequestUpsertOne) SetBankName(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetBankName(v)
	})
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateBankName() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateBankName()
	})
}

// SetAddress sets the "address" field.
func (u *ReimbursementRequestUpsertOne) SetAddress(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateAddress() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateAddress()
	})
}

// SetAmount sets the "amount" field.
func (u *ReimbursementRequestUpsertOne) SetAmount(v float64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReimbursementRequestUpsertOne) AddAmount(v float64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateAmount() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReimbursementRequestUpsertOne) SetStatus(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateStatus() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetPdfPath sets the "pdf_path" field.
func (u *ReimbursementRequestUpsertOne) SetPdfPath(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfPath(v)
	})
}

// UpdatePdfPath sets the "pdf_path" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdatePdfPath() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfPath()
	})
}

// SetPdfFileName sets the "pdf_file_name" field.
func (u *ReimbursementRequestUpsertOne) SetPdfFileName(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfFileName(v)
	})
}

// UpdatePdfFileName sets the "pdf_file_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdatePdfFileName() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfFileName()
	})
}

// SetPdfSize sets the "pdf_size" field.
func (u *ReimbursementRequestUpsertOne) SetPdfSize(v int64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfSize(v)
	})
}

// AddPdfSize adds v to the "pdf_size" field.
func (u *ReimbursementRequestUpsertOne) AddPdfSize(v int64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddPdfSize(v)
	})
}

// UpdatePdfSize sets the "pdf_size" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdatePdfSize() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfSize()
	})
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (u *ReimbursementRequestUpsertOne) SetPdfSha256(v string) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfSha256(v)
	})
}

// UpdatePdfSha256 sets the "pdf_sha256" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdatePdfSha256() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfSha256()
	})
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsertOne) SetPdfUploadedAt(v time.Time) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfUploadedAt(v)
	})
}

// UpdatePdfUploadedAt sets the "pdf_uploaded_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdatePdfUploadedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfUploadedAt()
	})
}

// ClearPdfUploadedAt clears the value of the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsertOne) ClearPdfUploadedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearPdfUploadedAt()
	})
}

// SetHandledBy sets the "handled_by" field.
func (u *ReimbursementRequestUpsertOne) SetHandledBy(v int64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetHandledBy(v)
	})
}

// AddHandledBy adds v to the "handled_by" field.
func (u *ReimbursementRequestUpsertOne) AddHandledBy(v int64) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddHandledBy(v)
	})
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateHandledBy() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateHandledBy()
	})
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *ReimbursementRequestUpsertOne) ClearHandledBy() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearHandledBy()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReimbursementRequestUpsertOne) SetCompletedAt(v time.Time) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateCompletedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReimbursementRequestUpsertOne) ClearCompletedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ReimbursementRequestUpsertOne) SetNotifiedAt(v time.Time) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateNotifiedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ReimbursementRequestUpsertOne) ClearNotifiedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReimbursementRequestUpsertOne) SetUpdatedAt(v time.Time) *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertOne) UpdateUpdatedAt() *ReimbursementRequestUpsertOne {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReimbursementRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReimbursementRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReimbursementRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReimbursementRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReimbursementRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReimbursementRequestCreateBulk is the builder for creating many ReimbursementRequest entities in bulk.
type ReimbursementRequestCreateBulk struct {
	config
	err      error
	builders []*ReimbursementRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the ReimbursementRequest entities in the database.
func (_c *ReimbursementRequestCreateBulk) Save(ctx context.Context) ([]*ReimbursementRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReimbursementRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReimbursementRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReimbursementRequestCreateBulk) SaveX(ctx context.Context) []*ReimbursementRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReimbursementRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReimbursementRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReimbursementRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReimbursementRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReimbursementRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReimbursementRequestUpsertBulk {
	_c.conflict = opts
	return &ReimbursementRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReimbursementRequestCreateBulk) OnConflictColumns(columns ...string) *ReimbursementRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReimbursementRequestUpsertBulk{
		create: _c,
	}
}

// ReimbursementRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of ReimbursementRequest nodes.
type ReimbursementRequestUpsertBulk struct {
	create *ReimbursementRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReimbursementRequestUpsertBulk) UpdateNewValues() *ReimbursementRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reimbursementrequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReimbursementRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReimbursementRequestUpsertBulk) Ignore() *ReimbursementRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReimbursementRequestUpsertBulk) DoNothing() *ReimbursementRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReimbursementRequestCreateBulk.OnConflict
// documentation for more info.
func (u *ReimbursementRequestUpsertBulk) Update(set func(*ReimbursementRequestUpsert)) *ReimbursementRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReimbursementRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ReimbursementRequestUpsertBulk) SetUserID(v int64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateUserID() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetRawText sets the "raw_text" field.
func (u *ReimbursementRequestUpsertBulk) SetRawText(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetRawText(v)
	})
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateRawText() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateRawText()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *ReimbursementRequestUpsertBulk) SetCompanyName(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateCompanyName() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateCompanyName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *ReimbursementRequestUpsertBulk) SetTaxID(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateTaxID() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateTaxID()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *ReimbursementRequestUpsertBulk) SetBankAccount(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateBankAccount() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// SetBankName sets the "bank_name" field.
func (u *ReimbursementRequestUpsertBulk) SetBankName(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetBankName(v)
	})
}

// UpdateBankName sets the "bank_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateBankName() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateBankName()
	})
}

// SetAddress sets the "address" field.
func (u *ReimbursementRequestUpsertBulk) SetAddress(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateAddress() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateAddress()
	})
}

// SetAmount sets the "amount" field.
func (u *ReimbursementRequestUpsertBulk) SetAmount(v float64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ReimbursementRequestUpsertBulk) AddAmount(v float64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateAmount() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReimbursementRequestUpsertBulk) SetStatus(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateStatus() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetPdfPath sets the "pdf_path" field.
func (u *ReimbursementRequestUpsertBulk) SetPdfPath(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfPath(v)
	})
}

// UpdatePdfPath sets the "pdf_path" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdatePdfPath() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfPath()
	})
}

// SetPdfFileName sets the "pdf_file_name" field.
func (u *ReimbursementRequestUpsertBulk) SetPdfFileName(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfFileName(v)
	})
}

// UpdatePdfFileName sets the "pdf_file_name" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdatePdfFileName() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfFileName()
	})
}

// SetPdfSize sets the "pdf_size" field.
func (u *ReimbursementRequestUpsertBulk) SetPdfSize(v int64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfSize(v)
	})
}

// AddPdfSize adds v to the "pdf_size" field.
func (u *ReimbursementRequestUpsertBulk) AddPdfSize(v int64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddPdfSize(v)
	})
}

// UpdatePdfSize sets the "pdf_size" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdatePdfSize() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfSize()
	})
}

// SetPdfSha256 sets the "pdf_sha256" field.
func (u *ReimbursementRequestUpsertBulk) SetPdfSha256(v string) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfSha256(v)
	})
}

// UpdatePdfSha256 sets the "pdf_sha256" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdatePdfSha256() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfSha256()
	})
}

// SetPdfUploadedAt sets the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsertBulk) SetPdfUploadedAt(v time.Time) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetPdfUploadedAt(v)
	})
}

// UpdatePdfUploadedAt sets the "pdf_uploaded_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdatePdfUploadedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdatePdfUploadedAt()
	})
}

// ClearPdfUploadedAt clears the value of the "pdf_uploaded_at" field.
func (u *ReimbursementRequestUpsertBulk) ClearPdfUploadedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearPdfUploadedAt()
	})
}

// SetHandledBy sets the "handled_by" field.
func (u *ReimbursementRequestUpsertBulk) SetHandledBy(v int64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetHandledBy(v)
	})
}

// AddHandledBy adds v to the "handled_by" field.
func (u *ReimbursementRequestUpsertBulk) AddHandledBy(v int64) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.AddHandledBy(v)
	})
}

// UpdateHandledBy sets the "handled_by" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateHandledBy() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateHandledBy()
	})
}

// ClearHandledBy clears the value of the "handled_by" field.
func (u *ReimbursementRequestUpsertBulk) ClearHandledBy() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearHandledBy()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ReimbursementRequestUpsertBulk) SetCompletedAt(v time.Time) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateCompletedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ReimbursementRequestUpsertBulk) ClearCompletedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearCompletedAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ReimbursementRequestUpsertBulk) SetNotifiedAt(v time.Time) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateNotifiedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ReimbursementRequestUpsertBulk) ClearNotifiedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ReimbursementRequestUpsertBulk) SetUpdatedAt(v time.Time) *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ReimbursementRequestUpsertBulk) UpdateUpdatedAt() *ReimbursementRequestUpsertBulk {
	return u.Update(func(s *ReimbursementRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ReimbursementRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReimbursementRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReimbursementRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReimbursementRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
