// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementperiod"
)

// SubscriptionEntitlementPeriodDelete is the builder for deleting a SubscriptionEntitlementPeriod entity.
type SubscriptionEntitlementPeriodDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionEntitlementPeriodMutation
}

// Where appends a list predicates to the SubscriptionEntitlementPeriodDelete builder.
func (_d *SubscriptionEntitlementPeriodDelete) Where(ps ...predicate.SubscriptionEntitlementPeriod) *SubscriptionEntitlementPeriodDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionEntitlementPeriodDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionEntitlementPeriodDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionEntitlementPeriodDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionentitlementperiod.Table, sqlgraph.NewFieldSpec(subscriptionentitlementperiod.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionEntitlementPeriodDeleteOne is the builder for deleting a single SubscriptionEntitlementPeriod entity.
type SubscriptionEntitlementPeriodDeleteOne struct {
	_d *SubscriptionEntitlementPeriodDelete
}

// Where appends a list predicates to the SubscriptionEntitlementPeriodDelete builder.
func (_d *SubscriptionEntitlementPeriodDeleteOne) Where(ps ...predicate.SubscriptionEntitlementPeriod) *SubscriptionEntitlementPeriodDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionEntitlementPeriodDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionentitlementperiod.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionEntitlementPeriodDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
