// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalancepackage"
)

// UserBalancePackageCreate is the builder for creating a UserBalancePackage entity.
type UserBalancePackageCreate struct {
	config
	mutation *UserBalancePackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserBalancePackageCreate) SetUserID(v int64) *UserBalancePackageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *UserBalancePackageCreate) SetPlanID(v int64) *UserBalancePackageCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *UserBalancePackageCreate) SetPaymentOrderID(v int64) *UserBalancePackageCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetWeeklyCreditUsd sets the "weekly_credit_usd" field.
func (_c *UserBalancePackageCreate) SetWeeklyCreditUsd(v float64) *UserBalancePackageCreate {
	_c.mutation.SetWeeklyCreditUsd(v)
	return _c
}

// SetCreditedCount sets the "credited_count" field.
func (_c *UserBalancePackageCreate) SetCreditedCount(v int) *UserBalancePackageCreate {
	_c.mutation.SetCreditedCount(v)
	return _c
}

// SetNillableCreditedCount sets the "credited_count" field if the given value is not nil.
func (_c *UserBalancePackageCreate) SetNillableCreditedCount(v *int) *UserBalancePackageCreate {
	if v != nil {
		_c.SetCreditedCount(*v)
	}
	return _c
}

// SetRefreshCount sets the "refresh_count" field.
func (_c *UserBalancePackageCreate) SetRefreshCount(v int) *UserBalancePackageCreate {
	_c.mutation.SetRefreshCount(v)
	return _c
}

// SetRefreshIntervalDays sets the "refresh_interval_days" field.
func (_c *UserBalancePackageCreate) SetRefreshIntervalDays(v int) *UserBalancePackageCreate {
	_c.mutation.SetRefreshIntervalDays(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserBalancePackageCreate) SetStartsAt(v time.Time) *UserBalancePackageCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNextCreditAt sets the "next_credit_at" field.
func (_c *UserBalancePackageCreate) SetNextCreditAt(v time.Time) *UserBalancePackageCreate {
	_c.mutation.SetNextCreditAt(v)
	return _c
}

// SetNillableNextCreditAt sets the "next_credit_at" field if the given value is not nil.
func (_c *UserBalancePackageCreate) SetNillableNextCreditAt(v *time.Time) *UserBalancePackageCreate {
	if v != nil {
		_c.SetNextCreditAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserBalancePackageCreate) SetExpiresAt(v time.Time) *UserBalancePackageCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserBalancePackageCreate) SetStatus(v string) *UserBalancePackageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserBalancePackageCreate) SetNillableStatus(v *string) *UserBalancePackageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserBalancePackageCreate) SetCreatedAt(v time.Time) *UserBalancePackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserBalancePackageCreate) SetNillableCreatedAt(v *time.Time) *UserBalancePackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserBalancePackageCreate) SetUpdatedAt(v time.Time) *UserBalancePackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserBalancePackageCreate) SetNillableUpdatedAt(v *time.Time) *UserBalancePackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserBalancePackageCreate) SetUser(v *User) *UserBalancePackageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserBalancePackageMutation object of the builder.
func (_c *UserBalancePackageCreate) Mutation() *UserBalancePackageMutation {
	return _c.mutation
}

// Save creates the UserBalancePackage in the database.
func (_c *UserBalancePackageCreate) Save(ctx context.Context) (*UserBalancePackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserBalancePackageCreate) SaveX(ctx context.Context) *UserBalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalancePackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalancePackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserBalancePackageCreate) defaults() {
	if _, ok := _c.mutation.CreditedCount(); !ok {
		v := userbalancepackage.DefaultCreditedCount
		_c.mutation.SetCreditedCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userbalancepackage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userbalancepackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userbalancepackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserBalancePackageCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserBalancePackage.user_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "UserBalancePackage.plan_id"`)}
	}
	if _, ok := _c.mutation.PaymentOrderID(); !ok {
		return &ValidationError{Name: "payment_order_id", err: errors.New(`ent: missing required field "UserBalancePackage.payment_order_id"`)}
	}
	if _, ok := _c.mutation.WeeklyCreditUsd(); !ok {
		return &ValidationError{Name: "weekly_credit_usd", err: errors.New(`ent: missing required field "UserBalancePackage.weekly_credit_usd"`)}
	}
	if _, ok := _c.mutation.CreditedCount(); !ok {
		return &ValidationError{Name: "credited_count", err: errors.New(`ent: missing required field "UserBalancePackage.credited_count"`)}
	}
	if _, ok := _c.mutation.RefreshCount(); !ok {
		return &ValidationError{Name: "refresh_count", err: errors.New(`ent: missing required field "UserBalancePackage.refresh_count"`)}
	}
	if _, ok := _c.mutation.RefreshIntervalDays(); !ok {
		return &ValidationError{Name: "refresh_interval_days", err: errors.New(`ent: missing required field "UserBalancePackage.refresh_interval_days"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserBalancePackage.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserBalancePackage.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserBalancePackage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userbalancepackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserBalancePackage.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserBalancePackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserBalancePackage.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserBalancePackage.user"`)}
	}
	return nil
}

func (_c *UserBalancePackageCreate) sqlSave(ctx context.Context) (*UserBalancePackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserBalancePackageCreate) createSpec() (*UserBalancePackage, *sqlgraph.CreateSpec) {
	var (
		_node = &UserBalancePackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userbalancepackage.Table, sqlgraph.NewFieldSpec(userbalancepackage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(userbalancepackage.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(userbalancepackage.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = value
	}
	if value, ok := _c.mutation.WeeklyCreditUsd(); ok {
		_spec.SetField(userbalancepackage.FieldWeeklyCreditUsd, field.TypeFloat64, value)
		_node.WeeklyCreditUsd = value
	}
	if value, ok := _c.mutation.CreditedCount(); ok {
		_spec.SetField(userbalancepackage.FieldCreditedCount, field.TypeInt, value)
		_node.CreditedCount = value
	}
	if value, ok := _c.mutation.RefreshCount(); ok {
		_spec.SetField(userbalancepackage.FieldRefreshCount, field.TypeInt, value)
		_node.RefreshCount = value
	}
	if value, ok := _c.mutation.RefreshIntervalDays(); ok {
		_spec.SetField(userbalancepackage.FieldRefreshIntervalDays, field.TypeInt, value)
		_node.RefreshIntervalDays = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(userbalancepackage.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.NextCreditAt(); ok {
		_spec.SetField(userbalancepackage.FieldNextCreditAt, field.TypeTime, value)
		_node.NextCreditAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userbalancepackage.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userbalancepackage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userbalancepackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalancepackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalancepackage.UserTable,
			Columns: []string{userbalancepackage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalancePackage.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalancePackageUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalancePackageCreate) OnConflict(opts ...sql.ConflictOption) *UserBalancePackageUpsertOne {
	_c.conflict = opts
	return &UserBalancePackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalancePackageCreate) OnConflictColumns(columns ...string) *UserBalancePackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalancePackageUpsertOne{
		create: _c,
	}
}

type (
	// UserBalancePackageUpsertOne is the builder for "upsert"-ing
	//  one UserBalancePackage node.
	UserBalancePackageUpsertOne struct {
		create *UserBalancePackageCreate
	}

	// UserBalancePackageUpsert is the "OnConflict" setter.
	UserBalancePackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserBalancePackageUpsert) SetUserID(v int64) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateUserID() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldUserID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UserBalancePackageUpsert) SetPlanID(v int64) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdatePlanID() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserBalancePackageUpsert) AddPlanID(v int64) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldPlanID, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserBalancePackageUpsert) SetPaymentOrderID(v int64) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdatePaymentOrderID() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *UserBalancePackageUpsert) AddPaymentOrderID(v int64) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldPaymentOrderID, v)
	return u
}

// SetWeeklyCreditUsd sets the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsert) SetWeeklyCreditUsd(v float64) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldWeeklyCreditUsd, v)
	return u
}

// UpdateWeeklyCreditUsd sets the "weekly_credit_usd" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateWeeklyCreditUsd() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldWeeklyCreditUsd)
	return u
}

// AddWeeklyCreditUsd adds v to the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsert) AddWeeklyCreditUsd(v float64) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldWeeklyCreditUsd, v)
	return u
}

// SetCreditedCount sets the "credited_count" field.
func (u *UserBalancePackageUpsert) SetCreditedCount(v int) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldCreditedCount, v)
	return u
}

// UpdateCreditedCount sets the "credited_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateCreditedCount() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldCreditedCount)
	return u
}

// AddCreditedCount adds v to the "credited_count" field.
func (u *UserBalancePackageUpsert) AddCreditedCount(v int) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldCreditedCount, v)
	return u
}

// SetRefreshCount sets the "refresh_count" field.
func (u *UserBalancePackageUpsert) SetRefreshCount(v int) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldRefreshCount, v)
	return u
}

// UpdateRefreshCount sets the "refresh_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateRefreshCount() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldRefreshCount)
	return u
}

// AddRefreshCount adds v to the "refresh_count" field.
func (u *UserBalancePackageUpsert) AddRefreshCount(v int) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldRefreshCount, v)
	return u
}

// SetRefreshIntervalDays sets the "refresh_interval_days" field.
func (u *UserBalancePackageUpsert) SetRefreshIntervalDays(v int) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldRefreshIntervalDays, v)
	return u
}

// UpdateRefreshIntervalDays sets the "refresh_interval_days" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateRefreshIntervalDays() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldRefreshIntervalDays)
	return u
}

// AddRefreshIntervalDays adds v to the "refresh_interval_days" field.
func (u *UserBalancePackageUpsert) AddRefreshIntervalDays(v int) *UserBalancePackageUpsert {
	u.Add(userbalancepackage.FieldRefreshIntervalDays, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserBalancePackageUpsert) SetStartsAt(v time.Time) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateStartsAt() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldStartsAt)
	return u
}

// SetNextCreditAt sets the "next_credit_at" field.
func (u *UserBalancePackageUpsert) SetNextCreditAt(v time.Time) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldNextCreditAt, v)
	return u
}

// UpdateNextCreditAt sets the "next_credit_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateNextCreditAt() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldNextCreditAt)
	return u
}

// ClearNextCreditAt clears the value of the "next_credit_at" field.
func (u *UserBalancePackageUpsert) ClearNextCreditAt() *UserBalancePackageUpsert {
	u.SetNull(userbalancepackage.FieldNextCreditAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalancePackageUpsert) SetExpiresAt(v time.Time) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateExpiresAt() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserBalancePackageUpsert) SetStatus(v string) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateStatus() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalancePackageUpsert) SetUpdatedAt(v time.Time) *UserBalancePackageUpsert {
	u.Set(userbalancepackage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsert) UpdateUpdatedAt() *UserBalancePackageUpsert {
	u.SetExcluded(userbalancepackage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalancePackageUpsertOne) UpdateNewValues() *UserBalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userbalancepackage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserBalancePackageUpsertOne) Ignore() *UserBalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalancePackageUpsertOne) DoNothing() *UserBalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalancePackageCreate.OnConflict
// documentation for more info.
func (u *UserBalancePackageUpsertOne) Update(set func(*UserBalancePackageUpsert)) *UserBalancePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserBalancePackageUpsertOne) SetUserID(v int64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateUserID() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserBalancePackageUpsertOne) SetPlanID(v int64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserBalancePackageUpsertOne) AddPlanID(v int64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdatePlanID() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdatePlanID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserBalancePackageUpsertOne) SetPaymentOrderID(v int64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *UserBalancePackageUpsertOne) AddPaymentOrderID(v int64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdatePaymentOrderID() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetWeeklyCreditUsd sets the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsertOne) SetWeeklyCreditUsd(v float64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetWeeklyCreditUsd(v)
	})
}

// AddWeeklyCreditUsd adds v to the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsertOne) AddWeeklyCreditUsd(v float64) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddWeeklyCreditUsd(v)
	})
}

// UpdateWeeklyCreditUsd sets the "weekly_credit_usd" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateWeeklyCreditUsd() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateWeeklyCreditUsd()
	})
}

// SetCreditedCount sets the "credited_count" field.
func (u *UserBalancePackageUpsertOne) SetCreditedCount(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetCreditedCount(v)
	})
}

// AddCreditedCount adds v to the "credited_count" field.
func (u *UserBalancePackageUpsertOne) AddCreditedCount(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddCreditedCount(v)
	})
}

// UpdateCreditedCount sets the "credited_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateCreditedCount() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateCreditedCount()
	})
}

// SetRefreshCount sets the "refresh_count" field.
func (u *UserBalancePackageUpsertOne) SetRefreshCount(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetRefreshCount(v)
	})
}

// AddRefreshCount adds v to the "refresh_count" field.
func (u *UserBalancePackageUpsertOne) AddRefreshCount(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddRefreshCount(v)
	})
}

// UpdateRefreshCount sets the "refresh_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateRefreshCount() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateRefreshCount()
	})
}

// SetRefreshIntervalDays sets the "refresh_interval_days" field.
func (u *UserBalancePackageUpsertOne) SetRefreshIntervalDays(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetRefreshIntervalDays(v)
	})
}

// AddRefreshIntervalDays adds v to the "refresh_interval_days" field.
func (u *UserBalancePackageUpsertOne) AddRefreshIntervalDays(v int) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddRefreshIntervalDays(v)
	})
}

// UpdateRefreshIntervalDays sets the "refresh_interval_days" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateRefreshIntervalDays() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateRefreshIntervalDays()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserBalancePackageUpsertOne) SetStartsAt(v time.Time) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateStartsAt() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateStartsAt()
	})
}

// SetNextCreditAt sets the "next_credit_at" field.
func (u *UserBalancePackageUpsertOne) SetNextCreditAt(v time.Time) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetNextCreditAt(v)
	})
}

// UpdateNextCreditAt sets the "next_credit_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateNextCreditAt() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateNextCreditAt()
	})
}

// ClearNextCreditAt clears the value of the "next_credit_at" field.
func (u *UserBalancePackageUpsertOne) ClearNextCreditAt() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.ClearNextCreditAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalancePackageUpsertOne) SetExpiresAt(v time.Time) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateExpiresAt() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserBalancePackageUpsertOne) SetStatus(v string) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateStatus() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalancePackageUpsertOne) SetUpdatedAt(v time.Time) *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertOne) UpdateUpdatedAt() *UserBalancePackageUpsertOne {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserBalancePackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalancePackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalancePackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserBalancePackageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserBalancePackageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserBalancePackageCreateBulk is the builder for creating many UserBalancePackage entities in bulk.
type UserBalancePackageCreateBulk struct {
	config
	err      error
	builders []*UserBalancePackageCreate
	conflict []sql.ConflictOption
}

// Save creates the UserBalancePackage entities in the database.
func (_c *UserBalancePackageCreateBulk) Save(ctx context.Context) ([]*UserBalancePackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserBalancePackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserBalancePackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserBalancePackageCreateBulk) SaveX(ctx context.Context) []*UserBalancePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalancePackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalancePackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalancePackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalancePackageUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalancePackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserBalancePackageUpsertBulk {
	_c.conflict = opts
	return &UserBalancePackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalancePackageCreateBulk) OnConflictColumns(columns ...string) *UserBalancePackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalancePackageUpsertBulk{
		create: _c,
	}
}

// UserBalancePackageUpsertBulk is the builder for "upsert"-ing
// a bulk of UserBalancePackage nodes.
type UserBalancePackageUpsertBulk struct {
	create *UserBalancePackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalancePackageUpsertBulk) UpdateNewValues() *UserBalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userbalancepackage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalancePackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserBalancePackageUpsertBulk) Ignore() *UserBalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalancePackageUpsertBulk) DoNothing() *UserBalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalancePackageCreateBulk.OnConflict
// documentation for more info.
func (u *UserBalancePackageUpsertBulk) Update(set func(*UserBalancePackageUpsert)) *UserBalancePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalancePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserBalancePackageUpsertBulk) SetUserID(v int64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateUserID() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserBalancePackageUpsertBulk) SetPlanID(v int64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserBalancePackageUpsertBulk) AddPlanID(v int64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdatePlanID() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdatePlanID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserBalancePackageUpsertBulk) SetPaymentOrderID(v int64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *UserBalancePackageUpsertBulk) AddPaymentOrderID(v int64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdatePaymentOrderID() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetWeeklyCreditUsd sets the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsertBulk) SetWeeklyCreditUsd(v float64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetWeeklyCreditUsd(v)
	})
}

// AddWeeklyCreditUsd adds v to the "weekly_credit_usd" field.
func (u *UserBalancePackageUpsertBulk) AddWeeklyCreditUsd(v float64) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddWeeklyCreditUsd(v)
	})
}

// UpdateWeeklyCreditUsd sets the "weekly_credit_usd" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateWeeklyCreditUsd() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateWeeklyCreditUsd()
	})
}

// SetCreditedCount sets the "credited_count" field.
func (u *UserBalancePackageUpsertBulk) SetCreditedCount(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetCreditedCount(v)
	})
}

// AddCreditedCount adds v to the "credited_count" field.
func (u *UserBalancePackageUpsertBulk) AddCreditedCount(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddCreditedCount(v)
	})
}

// UpdateCreditedCount sets the "credited_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateCreditedCount() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateCreditedCount()
	})
}

// SetRefreshCount sets the "refresh_count" field.
func (u *UserBalancePackageUpsertBulk) SetRefreshCount(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetRefreshCount(v)
	})
}

// AddRefreshCount adds v to the "refresh_count" field.
func (u *UserBalancePackageUpsertBulk) AddRefreshCount(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddRefreshCount(v)
	})
}

// UpdateRefreshCount sets the "refresh_count" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateRefreshCount() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateRefreshCount()
	})
}

// SetRefreshIntervalDays sets the "refresh_interval_days" field.
func (u *UserBalancePackageUpsertBulk) SetRefreshIntervalDays(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetRefreshIntervalDays(v)
	})
}

// AddRefreshIntervalDays adds v to the "refresh_interval_days" field.
func (u *UserBalancePackageUpsertBulk) AddRefreshIntervalDays(v int) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.AddRefreshIntervalDays(v)
	})
}

// UpdateRefreshIntervalDays sets the "refresh_interval_days" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateRefreshIntervalDays() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateRefreshIntervalDays()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserBalancePackageUpsertBulk) SetStartsAt(v time.Time) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateStartsAt() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateStartsAt()
	})
}

// SetNextCreditAt sets the "next_credit_at" field.
func (u *UserBalancePackageUpsertBulk) SetNextCreditAt(v time.Time) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetNextCreditAt(v)
	})
}

// UpdateNextCreditAt sets the "next_credit_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateNextCreditAt() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateNextCreditAt()
	})
}

// ClearNextCreditAt clears the value of the "next_credit_at" field.
func (u *UserBalancePackageUpsertBulk) ClearNextCreditAt() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.ClearNextCreditAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserBalancePackageUpsertBulk) SetExpiresAt(v time.Time) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateExpiresAt() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserBalancePackageUpsertBulk) SetStatus(v string) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateStatus() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalancePackageUpsertBulk) SetUpdatedAt(v time.Time) *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalancePackageUpsertBulk) UpdateUpdatedAt() *UserBalancePackageUpsertBulk {
	return u.Update(func(s *UserBalancePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserBalancePackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserBalancePackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalancePackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalancePackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
