// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalancepackage"
)

// UserBalancePackage is the model entity for the UserBalancePackage schema.
type UserBalancePackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID int64 `json:"payment_order_id,omitempty"`
	// WeeklyCreditUsd holds the value of the "weekly_credit_usd" field.
	WeeklyCreditUsd float64 `json:"weekly_credit_usd,omitempty"`
	// RemainingUsd holds the value of the "remaining_usd" field.
	RemainingUsd float64 `json:"remaining_usd,omitempty"`
	// CreditedCount holds the value of the "credited_count" field.
	CreditedCount int `json:"credited_count,omitempty"`
	// RefreshCount holds the value of the "refresh_count" field.
	RefreshCount int `json:"refresh_count,omitempty"`
	// RefreshIntervalDays holds the value of the "refresh_interval_days" field.
	RefreshIntervalDays int `json:"refresh_interval_days,omitempty"`
	// RenewalCount holds the value of the "renewal_count" field.
	RenewalCount int `json:"renewal_count,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// NextCreditAt holds the value of the "next_credit_at" field.
	NextCreditAt *time.Time `json:"next_credit_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserBalancePackageQuery when eager-loading is set.
	Edges        UserBalancePackageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserBalancePackageEdges holds the relations/edges for other nodes in the graph.
type UserBalancePackageEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBalancePackageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBalancePackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userbalancepackage.FieldWeeklyCreditUsd, userbalancepackage.FieldRemainingUsd:
			values[i] = new(sql.NullFloat64)
		case userbalancepackage.FieldID, userbalancepackage.FieldUserID, userbalancepackage.FieldPlanID, userbalancepackage.FieldPaymentOrderID, userbalancepackage.FieldCreditedCount, userbalancepackage.FieldRefreshCount, userbalancepackage.FieldRefreshIntervalDays, userbalancepackage.FieldRenewalCount:
			values[i] = new(sql.NullInt64)
		case userbalancepackage.FieldStatus:
			values[i] = new(sql.NullString)
		case userbalancepackage.FieldStartsAt, userbalancepackage.FieldNextCreditAt, userbalancepackage.FieldExpiresAt, userbalancepackage.FieldCreatedAt, userbalancepackage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBalancePackage fields.
func (_m *UserBalancePackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userbalancepackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userbalancepackage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userbalancepackage.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case userbalancepackage.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = value.Int64
			}
		case userbalancepackage.FieldWeeklyCreditUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_credit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyCreditUsd = value.Float64
			}
		case userbalancepackage.FieldRemainingUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_usd", values[i])
			} else if value.Valid {
				_m.RemainingUsd = value.Float64
			}
		case userbalancepackage.FieldCreditedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_count", values[i])
			} else if value.Valid {
				_m.CreditedCount = int(value.Int64)
			}
		case userbalancepackage.FieldRefreshCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_count", values[i])
			} else if value.Valid {
				_m.RefreshCount = int(value.Int64)
			}
		case userbalancepackage.FieldRefreshIntervalDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_days", values[i])
			} else if value.Valid {
				_m.RefreshIntervalDays = int(value.Int64)
			}
		case userbalancepackage.FieldRenewalCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field renewal_count", values[i])
			} else if value.Valid {
				_m.RenewalCount = int(value.Int64)
			}
		case userbalancepackage.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case userbalancepackage.FieldNextCreditAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_credit_at", values[i])
			} else if value.Valid {
				_m.NextCreditAt = new(time.Time)
				*_m.NextCreditAt = value.Time
			}
		case userbalancepackage.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case userbalancepackage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userbalancepackage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userbalancepackage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBalancePackage.
// This includes values selected through modifiers, order, etc.
func (_m *UserBalancePackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserBalancePackage entity.
func (_m *UserBalancePackage) QueryUser() *UserQuery {
	return NewUserBalancePackageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserBalancePackage.
// Note that you need to call UserBalancePackage.Unwrap() before calling this method if this UserBalancePackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserBalancePackage) Update() *UserBalancePackageUpdateOne {
	return NewUserBalancePackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserBalancePackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserBalancePackage) Unwrap() *UserBalancePackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBalancePackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserBalancePackage) String() string {
	var builder strings.Builder
	builder.WriteString("UserBalancePackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("payment_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentOrderID))
	builder.WriteString(", ")
	builder.WriteString("weekly_credit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyCreditUsd))
	builder.WriteString(", ")
	builder.WriteString("remaining_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemainingUsd))
	builder.WriteString(", ")
	builder.WriteString("credited_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditedCount))
	builder.WriteString(", ")
	builder.WriteString("refresh_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshCount))
	builder.WriteString(", ")
	builder.WriteString("refresh_interval_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshIntervalDays))
	builder.WriteString(", ")
	builder.WriteString("renewal_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RenewalCount))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.NextCreditAt; v != nil {
		builder.WriteString("next_credit_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserBalancePackages is a parsable slice of UserBalancePackage.
type UserBalancePackages []*UserBalancePackage
