// Code generated by ent, DO NOT EDIT.

package balancepackageplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldName, v))
}

// PriceCny applies equality check predicate on the "price_cny" field. It's identical to PriceCnyEQ.
func PriceCny(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldPriceCny, v))
}

// WeeklyCreditUsd applies equality check predicate on the "weekly_credit_usd" field. It's identical to WeeklyCreditUsdEQ.
func WeeklyCreditUsd(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldWeeklyCreditUsd, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldValidityDays, v))
}

// RefreshCount applies equality check predicate on the "refresh_count" field. It's identical to RefreshCountEQ.
func RefreshCount(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldRefreshCount, v))
}

// RefreshIntervalDays applies equality check predicate on the "refresh_interval_days" field. It's identical to RefreshIntervalDaysEQ.
func RefreshIntervalDays(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldRefreshIntervalDays, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldContainsFold(FieldName, v))
}

// PriceCnyEQ applies the EQ predicate on the "price_cny" field.
func PriceCnyEQ(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldPriceCny, v))
}

// PriceCnyNEQ applies the NEQ predicate on the "price_cny" field.
func PriceCnyNEQ(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldPriceCny, v))
}

// PriceCnyIn applies the In predicate on the "price_cny" field.
func PriceCnyIn(vs ...float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldPriceCny, vs...))
}

// PriceCnyNotIn applies the NotIn predicate on the "price_cny" field.
func PriceCnyNotIn(vs ...float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldPriceCny, vs...))
}

// PriceCnyGT applies the GT predicate on the "price_cny" field.
func PriceCnyGT(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldPriceCny, v))
}

// PriceCnyGTE applies the GTE predicate on the "price_cny" field.
func PriceCnyGTE(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldPriceCny, v))
}

// PriceCnyLT applies the LT predicate on the "price_cny" field.
func PriceCnyLT(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldPriceCny, v))
}

// PriceCnyLTE applies the LTE predicate on the "price_cny" field.
func PriceCnyLTE(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldPriceCny, v))
}

// WeeklyCreditUsdEQ applies the EQ predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdEQ(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldWeeklyCreditUsd, v))
}

// WeeklyCreditUsdNEQ applies the NEQ predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdNEQ(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldWeeklyCreditUsd, v))
}

// WeeklyCreditUsdIn applies the In predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdIn(vs ...float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldWeeklyCreditUsd, vs...))
}

// WeeklyCreditUsdNotIn applies the NotIn predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdNotIn(vs ...float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldWeeklyCreditUsd, vs...))
}

// WeeklyCreditUsdGT applies the GT predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdGT(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldWeeklyCreditUsd, v))
}

// WeeklyCreditUsdGTE applies the GTE predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdGTE(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldWeeklyCreditUsd, v))
}

// WeeklyCreditUsdLT applies the LT predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdLT(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldWeeklyCreditUsd, v))
}

// WeeklyCreditUsdLTE applies the LTE predicate on the "weekly_credit_usd" field.
func WeeklyCreditUsdLTE(v float64) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldWeeklyCreditUsd, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldValidityDays, v))
}

// RefreshCountEQ applies the EQ predicate on the "refresh_count" field.
func RefreshCountEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldRefreshCount, v))
}

// RefreshCountNEQ applies the NEQ predicate on the "refresh_count" field.
func RefreshCountNEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldRefreshCount, v))
}

// RefreshCountIn applies the In predicate on the "refresh_count" field.
func RefreshCountIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldRefreshCount, vs...))
}

// RefreshCountNotIn applies the NotIn predicate on the "refresh_count" field.
func RefreshCountNotIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldRefreshCount, vs...))
}

// RefreshCountGT applies the GT predicate on the "refresh_count" field.
func RefreshCountGT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldRefreshCount, v))
}

// RefreshCountGTE applies the GTE predicate on the "refresh_count" field.
func RefreshCountGTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldRefreshCount, v))
}

// RefreshCountLT applies the LT predicate on the "refresh_count" field.
func RefreshCountLT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldRefreshCount, v))
}

// RefreshCountLTE applies the LTE predicate on the "refresh_count" field.
func RefreshCountLTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldRefreshCount, v))
}

// RefreshIntervalDaysEQ applies the EQ predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldRefreshIntervalDays, v))
}

// RefreshIntervalDaysNEQ applies the NEQ predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysNEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldRefreshIntervalDays, v))
}

// RefreshIntervalDaysIn applies the In predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldRefreshIntervalDays, vs...))
}

// RefreshIntervalDaysNotIn applies the NotIn predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysNotIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldRefreshIntervalDays, vs...))
}

// RefreshIntervalDaysGT applies the GT predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysGT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldRefreshIntervalDays, v))
}

// RefreshIntervalDaysGTE applies the GTE predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysGTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldRefreshIntervalDays, v))
}

// RefreshIntervalDaysLT applies the LT predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysLT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldRefreshIntervalDays, v))
}

// RefreshIntervalDaysLTE applies the LTE predicate on the "refresh_interval_days" field.
func RefreshIntervalDaysLTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldRefreshIntervalDays, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalancePackagePlan) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalancePackagePlan) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalancePackagePlan) predicate.BalancePackagePlan {
	return predicate.BalancePackagePlan(sql.NotPredicates(p))
}
