// Code generated by ent, DO NOT EDIT.

package paymentbalancehold

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldOrderID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldExpiresAt, v))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldCapturedAt, v))
}

// ReleasedAt applies equality check predicate on the "released_at" field. It's identical to ReleasedAtEQ.
func ReleasedAt(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleaseReason applies equality check predicate on the "release_reason" field. It's identical to ReleaseReasonEQ.
func ReleaseReason(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldReleaseReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldOrderID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldExpiresAt, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldCapturedAt, v))
}

// CapturedAtIsNil applies the IsNil predicate on the "captured_at" field.
func CapturedAtIsNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIsNull(FieldCapturedAt))
}

// CapturedAtNotNil applies the NotNil predicate on the "captured_at" field.
func CapturedAtNotNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotNull(FieldCapturedAt))
}

// ReleasedAtEQ applies the EQ predicate on the "released_at" field.
func ReleasedAtEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleasedAtNEQ applies the NEQ predicate on the "released_at" field.
func ReleasedAtNEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldReleasedAt, v))
}

// ReleasedAtIn applies the In predicate on the "released_at" field.
func ReleasedAtIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldReleasedAt, vs...))
}

// ReleasedAtNotIn applies the NotIn predicate on the "released_at" field.
func ReleasedAtNotIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldReleasedAt, vs...))
}

// ReleasedAtGT applies the GT predicate on the "released_at" field.
func ReleasedAtGT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldReleasedAt, v))
}

// ReleasedAtGTE applies the GTE predicate on the "released_at" field.
func ReleasedAtGTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldReleasedAt, v))
}

// ReleasedAtLT applies the LT predicate on the "released_at" field.
func ReleasedAtLT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldReleasedAt, v))
}

// ReleasedAtLTE applies the LTE predicate on the "released_at" field.
func ReleasedAtLTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldReleasedAt, v))
}

// ReleasedAtIsNil applies the IsNil predicate on the "released_at" field.
func ReleasedAtIsNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIsNull(FieldReleasedAt))
}

// ReleasedAtNotNil applies the NotNil predicate on the "released_at" field.
func ReleasedAtNotNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotNull(FieldReleasedAt))
}

// ReleaseReasonEQ applies the EQ predicate on the "release_reason" field.
func ReleaseReasonEQ(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldReleaseReason, v))
}

// ReleaseReasonNEQ applies the NEQ predicate on the "release_reason" field.
func ReleaseReasonNEQ(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldReleaseReason, v))
}

// ReleaseReasonIn applies the In predicate on the "release_reason" field.
func ReleaseReasonIn(vs ...string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldReleaseReason, vs...))
}

// ReleaseReasonNotIn applies the NotIn predicate on the "release_reason" field.
func ReleaseReasonNotIn(vs ...string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldReleaseReason, vs...))
}

// ReleaseReasonGT applies the GT predicate on the "release_reason" field.
func ReleaseReasonGT(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldReleaseReason, v))
}

// ReleaseReasonGTE applies the GTE predicate on the "release_reason" field.
func ReleaseReasonGTE(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldReleaseReason, v))
}

// ReleaseReasonLT applies the LT predicate on the "release_reason" field.
func ReleaseReasonLT(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldReleaseReason, v))
}

// ReleaseReasonLTE applies the LTE predicate on the "release_reason" field.
func ReleaseReasonLTE(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldReleaseReason, v))
}

// ReleaseReasonContains applies the Contains predicate on the "release_reason" field.
func ReleaseReasonContains(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldContains(FieldReleaseReason, v))
}

// ReleaseReasonHasPrefix applies the HasPrefix predicate on the "release_reason" field.
func ReleaseReasonHasPrefix(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldHasPrefix(FieldReleaseReason, v))
}

// ReleaseReasonHasSuffix applies the HasSuffix predicate on the "release_reason" field.
func ReleaseReasonHasSuffix(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldHasSuffix(FieldReleaseReason, v))
}

// ReleaseReasonIsNil applies the IsNil predicate on the "release_reason" field.
func ReleaseReasonIsNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIsNull(FieldReleaseReason))
}

// ReleaseReasonNotNil applies the NotNil predicate on the "release_reason" field.
func ReleaseReasonNotNil() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotNull(FieldReleaseReason))
}

// ReleaseReasonEqualFold applies the EqualFold predicate on the "release_reason" field.
func ReleaseReasonEqualFold(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEqualFold(FieldReleaseReason, v))
}

// ReleaseReasonContainsFold applies the ContainsFold predicate on the "release_reason" field.
func ReleaseReasonContainsFold(v string) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldContainsFold(FieldReleaseReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentBalanceHold) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentBalanceHold) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentBalanceHold) predicate.PaymentBalanceHold {
	return predicate.PaymentBalanceHold(sql.NotPredicates(p))
}
