// Code generated by ent, DO NOT EDIT.

package subscriptionquotadebtadjustment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionquotadebtadjustment type in the database.
	Label = "subscription_quota_debt_adjustment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSourceKey holds the string denoting the source_key field in the database.
	FieldSourceKey = "source_key"
	// FieldOverageUsd holds the string denoting the overage_usd field in the database.
	FieldOverageUsd = "overage_usd"
	// FieldWeeklyLimitUsd holds the string denoting the weekly_limit_usd field in the database.
	FieldWeeklyLimitUsd = "weekly_limit_usd"
	// FieldDailyEquivalentUsd holds the string denoting the daily_equivalent_usd field in the database.
	FieldDailyEquivalentUsd = "daily_equivalent_usd"
	// FieldRawDeductionDays holds the string denoting the raw_deduction_days field in the database.
	FieldRawDeductionDays = "raw_deduction_days"
	// FieldDeductedDays holds the string denoting the deducted_days field in the database.
	FieldDeductedDays = "deducted_days"
	// FieldOriginalExpiresAt holds the string denoting the original_expires_at field in the database.
	FieldOriginalExpiresAt = "original_expires_at"
	// FieldNewExpiresAt holds the string denoting the new_expires_at field in the database.
	FieldNewExpiresAt = "new_expires_at"
	// FieldApplicationStatus holds the string denoting the application_status field in the database.
	FieldApplicationStatus = "application_status"
	// FieldAppliedAt holds the string denoting the applied_at field in the database.
	FieldAppliedAt = "applied_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeSubscription holds the string denoting the subscription edge name in mutations.
	EdgeSubscription = "subscription"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the subscriptionquotadebtadjustment in the database.
	Table = "subscription_quota_debt_adjustments"
	// SubscriptionTable is the table that holds the subscription relation/edge.
	SubscriptionTable = "subscription_quota_debt_adjustments"
	// SubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	SubscriptionInverseTable = "user_subscriptions"
	// SubscriptionColumn is the table column denoting the subscription relation/edge.
	SubscriptionColumn = "subscription_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "subscription_quota_debt_adjustments"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "subscription_quota_debt_adjustments"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for subscriptionquotadebtadjustment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSubscriptionID,
	FieldUserID,
	FieldGroupID,
	FieldSourceKey,
	FieldOverageUsd,
	FieldWeeklyLimitUsd,
	FieldDailyEquivalentUsd,
	FieldRawDeductionDays,
	FieldDeductedDays,
	FieldOriginalExpiresAt,
	FieldNewExpiresAt,
	FieldApplicationStatus,
	FieldAppliedAt,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SourceKeyValidator is a validator for the "source_key" field. It is called by the builders before save.
	SourceKeyValidator func(string) error
	// ApplicationStatusValidator is a validator for the "application_status" field. It is called by the builders before save.
	ApplicationStatusValidator func(string) error
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
)

// OrderOption defines the ordering options for the SubscriptionQuotaDebtAdjustment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySourceKey orders the results by the source_key field.
func BySourceKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceKey, opts...).ToFunc()
}

// ByOverageUsd orders the results by the overage_usd field.
func ByOverageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverageUsd, opts...).ToFunc()
}

// ByWeeklyLimitUsd orders the results by the weekly_limit_usd field.
func ByWeeklyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyLimitUsd, opts...).ToFunc()
}

// ByDailyEquivalentUsd orders the results by the daily_equivalent_usd field.
func ByDailyEquivalentUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyEquivalentUsd, opts...).ToFunc()
}

// ByRawDeductionDays orders the results by the raw_deduction_days field.
func ByRawDeductionDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawDeductionDays, opts...).ToFunc()
}

// ByDeductedDays orders the results by the deducted_days field.
func ByDeductedDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductedDays, opts...).ToFunc()
}

// ByOriginalExpiresAt orders the results by the original_expires_at field.
func ByOriginalExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalExpiresAt, opts...).ToFunc()
}

// ByNewExpiresAt orders the results by the new_expires_at field.
func ByNewExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewExpiresAt, opts...).ToFunc()
}

// ByApplicationStatus orders the results by the application_status field.
func ByApplicationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationStatus, opts...).ToFunc()
}

// ByAppliedAt orders the results by the applied_at field.
func ByAppliedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySubscriptionField orders the results by subscription field.
func BySubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
