// Code generated by ent, DO NOT EDIT.

package subscriptionquotadebtadjustment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldSubscriptionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldGroupID, v))
}

// SourceKey applies equality check predicate on the "source_key" field. It's identical to SourceKeyEQ.
func SourceKey(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldSourceKey, v))
}

// OverageUsd applies equality check predicate on the "overage_usd" field. It's identical to OverageUsdEQ.
func OverageUsd(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldOverageUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// DailyEquivalentUsd applies equality check predicate on the "daily_equivalent_usd" field. It's identical to DailyEquivalentUsdEQ.
func DailyEquivalentUsd(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldDailyEquivalentUsd, v))
}

// RawDeductionDays applies equality check predicate on the "raw_deduction_days" field. It's identical to RawDeductionDaysEQ.
func RawDeductionDays(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldRawDeductionDays, v))
}

// DeductedDays applies equality check predicate on the "deducted_days" field. It's identical to DeductedDaysEQ.
func DeductedDays(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldDeductedDays, v))
}

// OriginalExpiresAt applies equality check predicate on the "original_expires_at" field. It's identical to OriginalExpiresAtEQ.
func OriginalExpiresAt(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldOriginalExpiresAt, v))
}

// NewExpiresAt applies equality check predicate on the "new_expires_at" field. It's identical to NewExpiresAtEQ.
func NewExpiresAt(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldNewExpiresAt, v))
}

// ApplicationStatus applies equality check predicate on the "application_status" field. It's identical to ApplicationStatusEQ.
func ApplicationStatus(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldApplicationStatus, v))
}

// AppliedAt applies equality check predicate on the "applied_at" field. It's identical to AppliedAtEQ.
func AppliedAt(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldAppliedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldUserID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldGroupID, vs...))
}

// SourceKeyEQ applies the EQ predicate on the "source_key" field.
func SourceKeyEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldSourceKey, v))
}

// SourceKeyNEQ applies the NEQ predicate on the "source_key" field.
func SourceKeyNEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldSourceKey, v))
}

// SourceKeyIn applies the In predicate on the "source_key" field.
func SourceKeyIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldSourceKey, vs...))
}

// SourceKeyNotIn applies the NotIn predicate on the "source_key" field.
func SourceKeyNotIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldSourceKey, vs...))
}

// SourceKeyGT applies the GT predicate on the "source_key" field.
func SourceKeyGT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldSourceKey, v))
}

// SourceKeyGTE applies the GTE predicate on the "source_key" field.
func SourceKeyGTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldSourceKey, v))
}

// SourceKeyLT applies the LT predicate on the "source_key" field.
func SourceKeyLT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldSourceKey, v))
}

// SourceKeyLTE applies the LTE predicate on the "source_key" field.
func SourceKeyLTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldSourceKey, v))
}

// SourceKeyContains applies the Contains predicate on the "source_key" field.
func SourceKeyContains(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContains(FieldSourceKey, v))
}

// SourceKeyHasPrefix applies the HasPrefix predicate on the "source_key" field.
func SourceKeyHasPrefix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasPrefix(FieldSourceKey, v))
}

// SourceKeyHasSuffix applies the HasSuffix predicate on the "source_key" field.
func SourceKeyHasSuffix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasSuffix(FieldSourceKey, v))
}

// SourceKeyEqualFold applies the EqualFold predicate on the "source_key" field.
func SourceKeyEqualFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEqualFold(FieldSourceKey, v))
}

// SourceKeyContainsFold applies the ContainsFold predicate on the "source_key" field.
func SourceKeyContainsFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContainsFold(FieldSourceKey, v))
}

// OverageUsdEQ applies the EQ predicate on the "overage_usd" field.
func OverageUsdEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldOverageUsd, v))
}

// OverageUsdNEQ applies the NEQ predicate on the "overage_usd" field.
func OverageUsdNEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldOverageUsd, v))
}

// OverageUsdIn applies the In predicate on the "overage_usd" field.
func OverageUsdIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldOverageUsd, vs...))
}

// OverageUsdNotIn applies the NotIn predicate on the "overage_usd" field.
func OverageUsdNotIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldOverageUsd, vs...))
}

// OverageUsdGT applies the GT predicate on the "overage_usd" field.
func OverageUsdGT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldOverageUsd, v))
}

// OverageUsdGTE applies the GTE predicate on the "overage_usd" field.
func OverageUsdGTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldOverageUsd, v))
}

// OverageUsdLT applies the LT predicate on the "overage_usd" field.
func OverageUsdLT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldOverageUsd, v))
}

// OverageUsdLTE applies the LTE predicate on the "overage_usd" field.
func OverageUsdLTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldOverageUsd, v))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// DailyEquivalentUsdEQ applies the EQ predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldDailyEquivalentUsd, v))
}

// DailyEquivalentUsdNEQ applies the NEQ predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdNEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldDailyEquivalentUsd, v))
}

// DailyEquivalentUsdIn applies the In predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldDailyEquivalentUsd, vs...))
}

// DailyEquivalentUsdNotIn applies the NotIn predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdNotIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldDailyEquivalentUsd, vs...))
}

// DailyEquivalentUsdGT applies the GT predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdGT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldDailyEquivalentUsd, v))
}

// DailyEquivalentUsdGTE applies the GTE predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdGTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldDailyEquivalentUsd, v))
}

// DailyEquivalentUsdLT applies the LT predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdLT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldDailyEquivalentUsd, v))
}

// DailyEquivalentUsdLTE applies the LTE predicate on the "daily_equivalent_usd" field.
func DailyEquivalentUsdLTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldDailyEquivalentUsd, v))
}

// RawDeductionDaysEQ applies the EQ predicate on the "raw_deduction_days" field.
func RawDeductionDaysEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldRawDeductionDays, v))
}

// RawDeductionDaysNEQ applies the NEQ predicate on the "raw_deduction_days" field.
func RawDeductionDaysNEQ(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldRawDeductionDays, v))
}

// RawDeductionDaysIn applies the In predicate on the "raw_deduction_days" field.
func RawDeductionDaysIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldRawDeductionDays, vs...))
}

// RawDeductionDaysNotIn applies the NotIn predicate on the "raw_deduction_days" field.
func RawDeductionDaysNotIn(vs ...float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldRawDeductionDays, vs...))
}

// RawDeductionDaysGT applies the GT predicate on the "raw_deduction_days" field.
func RawDeductionDaysGT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldRawDeductionDays, v))
}

// RawDeductionDaysGTE applies the GTE predicate on the "raw_deduction_days" field.
func RawDeductionDaysGTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldRawDeductionDays, v))
}

// RawDeductionDaysLT applies the LT predicate on the "raw_deduction_days" field.
func RawDeductionDaysLT(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldRawDeductionDays, v))
}

// RawDeductionDaysLTE applies the LTE predicate on the "raw_deduction_days" field.
func RawDeductionDaysLTE(v float64) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldRawDeductionDays, v))
}

// DeductedDaysEQ applies the EQ predicate on the "deducted_days" field.
func DeductedDaysEQ(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldDeductedDays, v))
}

// DeductedDaysNEQ applies the NEQ predicate on the "deducted_days" field.
func DeductedDaysNEQ(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldDeductedDays, v))
}

// DeductedDaysIn applies the In predicate on the "deducted_days" field.
func DeductedDaysIn(vs ...int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldDeductedDays, vs...))
}

// DeductedDaysNotIn applies the NotIn predicate on the "deducted_days" field.
func DeductedDaysNotIn(vs ...int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldDeductedDays, vs...))
}

// DeductedDaysGT applies the GT predicate on the "deducted_days" field.
func DeductedDaysGT(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldDeductedDays, v))
}

// DeductedDaysGTE applies the GTE predicate on the "deducted_days" field.
func DeductedDaysGTE(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldDeductedDays, v))
}

// DeductedDaysLT applies the LT predicate on the "deducted_days" field.
func DeductedDaysLT(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldDeductedDays, v))
}

// DeductedDaysLTE applies the LTE predicate on the "deducted_days" field.
func DeductedDaysLTE(v int) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldDeductedDays, v))
}

// OriginalExpiresAtEQ applies the EQ predicate on the "original_expires_at" field.
func OriginalExpiresAtEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldOriginalExpiresAt, v))
}

// OriginalExpiresAtNEQ applies the NEQ predicate on the "original_expires_at" field.
func OriginalExpiresAtNEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldOriginalExpiresAt, v))
}

// OriginalExpiresAtIn applies the In predicate on the "original_expires_at" field.
func OriginalExpiresAtIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldOriginalExpiresAt, vs...))
}

// OriginalExpiresAtNotIn applies the NotIn predicate on the "original_expires_at" field.
func OriginalExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldOriginalExpiresAt, vs...))
}

// OriginalExpiresAtGT applies the GT predicate on the "original_expires_at" field.
func OriginalExpiresAtGT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldOriginalExpiresAt, v))
}

// OriginalExpiresAtGTE applies the GTE predicate on the "original_expires_at" field.
func OriginalExpiresAtGTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldOriginalExpiresAt, v))
}

// OriginalExpiresAtLT applies the LT predicate on the "original_expires_at" field.
func OriginalExpiresAtLT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldOriginalExpiresAt, v))
}

// OriginalExpiresAtLTE applies the LTE predicate on the "original_expires_at" field.
func OriginalExpiresAtLTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldOriginalExpiresAt, v))
}

// NewExpiresAtEQ applies the EQ predicate on the "new_expires_at" field.
func NewExpiresAtEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldNewExpiresAt, v))
}

// NewExpiresAtNEQ applies the NEQ predicate on the "new_expires_at" field.
func NewExpiresAtNEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldNewExpiresAt, v))
}

// NewExpiresAtIn applies the In predicate on the "new_expires_at" field.
func NewExpiresAtIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldNewExpiresAt, vs...))
}

// NewExpiresAtNotIn applies the NotIn predicate on the "new_expires_at" field.
func NewExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldNewExpiresAt, vs...))
}

// NewExpiresAtGT applies the GT predicate on the "new_expires_at" field.
func NewExpiresAtGT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldNewExpiresAt, v))
}

// NewExpiresAtGTE applies the GTE predicate on the "new_expires_at" field.
func NewExpiresAtGTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldNewExpiresAt, v))
}

// NewExpiresAtLT applies the LT predicate on the "new_expires_at" field.
func NewExpiresAtLT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldNewExpiresAt, v))
}

// NewExpiresAtLTE applies the LTE predicate on the "new_expires_at" field.
func NewExpiresAtLTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldNewExpiresAt, v))
}

// ApplicationStatusEQ applies the EQ predicate on the "application_status" field.
func ApplicationStatusEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldApplicationStatus, v))
}

// ApplicationStatusNEQ applies the NEQ predicate on the "application_status" field.
func ApplicationStatusNEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldApplicationStatus, v))
}

// ApplicationStatusIn applies the In predicate on the "application_status" field.
func ApplicationStatusIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldApplicationStatus, vs...))
}

// ApplicationStatusNotIn applies the NotIn predicate on the "application_status" field.
func ApplicationStatusNotIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldApplicationStatus, vs...))
}

// ApplicationStatusGT applies the GT predicate on the "application_status" field.
func ApplicationStatusGT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldApplicationStatus, v))
}

// ApplicationStatusGTE applies the GTE predicate on the "application_status" field.
func ApplicationStatusGTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldApplicationStatus, v))
}

// ApplicationStatusLT applies the LT predicate on the "application_status" field.
func ApplicationStatusLT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldApplicationStatus, v))
}

// ApplicationStatusLTE applies the LTE predicate on the "application_status" field.
func ApplicationStatusLTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldApplicationStatus, v))
}

// ApplicationStatusContains applies the Contains predicate on the "application_status" field.
func ApplicationStatusContains(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContains(FieldApplicationStatus, v))
}

// ApplicationStatusHasPrefix applies the HasPrefix predicate on the "application_status" field.
func ApplicationStatusHasPrefix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasPrefix(FieldApplicationStatus, v))
}

// ApplicationStatusHasSuffix applies the HasSuffix predicate on the "application_status" field.
func ApplicationStatusHasSuffix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasSuffix(FieldApplicationStatus, v))
}

// ApplicationStatusEqualFold applies the EqualFold predicate on the "application_status" field.
func ApplicationStatusEqualFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEqualFold(FieldApplicationStatus, v))
}

// ApplicationStatusContainsFold applies the ContainsFold predicate on the "application_status" field.
func ApplicationStatusContainsFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContainsFold(FieldApplicationStatus, v))
}

// AppliedAtEQ applies the EQ predicate on the "applied_at" field.
func AppliedAtEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldAppliedAt, v))
}

// AppliedAtNEQ applies the NEQ predicate on the "applied_at" field.
func AppliedAtNEQ(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldAppliedAt, v))
}

// AppliedAtIn applies the In predicate on the "applied_at" field.
func AppliedAtIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldAppliedAt, vs...))
}

// AppliedAtNotIn applies the NotIn predicate on the "applied_at" field.
func AppliedAtNotIn(vs ...time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldAppliedAt, vs...))
}

// AppliedAtGT applies the GT predicate on the "applied_at" field.
func AppliedAtGT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldAppliedAt, v))
}

// AppliedAtGTE applies the GTE predicate on the "applied_at" field.
func AppliedAtGTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldAppliedAt, v))
}

// AppliedAtLT applies the LT predicate on the "applied_at" field.
func AppliedAtLT(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldAppliedAt, v))
}

// AppliedAtLTE applies the LTE predicate on the "applied_at" field.
func AppliedAtLTE(v time.Time) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldAppliedAt, v))
}

// AppliedAtIsNil applies the IsNil predicate on the "applied_at" field.
func AppliedAtIsNil() predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIsNull(FieldAppliedAt))
}

// AppliedAtNotNil applies the NotNil predicate on the "applied_at" field.
func AppliedAtNotNil() predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotNull(FieldAppliedAt))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.FieldContainsFold(FieldNotes, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionQuotaDebtAdjustment) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionQuotaDebtAdjustment) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionQuotaDebtAdjustment) predicate.SubscriptionQuotaDebtAdjustment {
	return predicate.SubscriptionQuotaDebtAdjustment(sql.NotPredicates(p))
}
