// Code generated by ent, DO NOT EDIT.

package redeemcard

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the redeemcard type in the database.
	Label = "redeem_card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldLastViewedAt holds the string denoting the last_viewed_at field in the database.
	FieldLastViewedAt = "last_viewed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the redeemcard in the database.
	Table = "redeem_cards"
)

// Columns holds all SQL columns for redeemcard fields.
var Columns = []string{
	FieldID,
	FieldToken,
	FieldRedeemCodeID,
	FieldTheme,
	FieldContent,
	FieldCreatedBy,
	FieldViewCount,
	FieldLastViewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultTheme holds the default value on creation for the "theme" field.
	DefaultTheme string
	// ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	ThemeValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent func() map[string]interface{}
	// DefaultViewCount holds the default value on creation for the "view_count" field.
	DefaultViewCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RedeemCard queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByLastViewedAt orders the results by the last_viewed_at field.
func ByLastViewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastViewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
