// Code generated by ent, DO NOT EDIT.

package redeemcard

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldID, id))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldToken, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldRedeemCodeID, v))
}

// Theme applies equality check predicate on the "theme" field. It's identical to ThemeEQ.
func Theme(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldTheme, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldCreatedBy, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldViewCount, v))
}

// LastViewedAt applies equality check predicate on the "last_viewed_at" field. It's identical to LastViewedAtEQ.
func LastViewedAt(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldLastViewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldContainsFold(FieldToken, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldRedeemCodeID, v))
}

// ThemeEQ applies the EQ predicate on the "theme" field.
func ThemeEQ(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldTheme, v))
}

// ThemeNEQ applies the NEQ predicate on the "theme" field.
func ThemeNEQ(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldTheme, v))
}

// ThemeIn applies the In predicate on the "theme" field.
func ThemeIn(vs ...string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldTheme, vs...))
}

// ThemeNotIn applies the NotIn predicate on the "theme" field.
func ThemeNotIn(vs ...string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldTheme, vs...))
}

// ThemeGT applies the GT predicate on the "theme" field.
func ThemeGT(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldTheme, v))
}

// ThemeGTE applies the GTE predicate on the "theme" field.
func ThemeGTE(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldTheme, v))
}

// ThemeLT applies the LT predicate on the "theme" field.
func ThemeLT(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldTheme, v))
}

// ThemeLTE applies the LTE predicate on the "theme" field.
func ThemeLTE(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldTheme, v))
}

// ThemeContains applies the Contains predicate on the "theme" field.
func ThemeContains(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldContains(FieldTheme, v))
}

// ThemeHasPrefix applies the HasPrefix predicate on the "theme" field.
func ThemeHasPrefix(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldHasPrefix(FieldTheme, v))
}

// ThemeHasSuffix applies the HasSuffix predicate on the "theme" field.
func ThemeHasSuffix(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldHasSuffix(FieldTheme, v))
}

// ThemeEqualFold applies the EqualFold predicate on the "theme" field.
func ThemeEqualFold(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEqualFold(FieldTheme, v))
}

// ThemeContainsFold applies the ContainsFold predicate on the "theme" field.
func ThemeContainsFold(v string) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldContainsFold(FieldTheme, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotNull(FieldCreatedBy))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldViewCount, v))
}

// LastViewedAtEQ applies the EQ predicate on the "last_viewed_at" field.
func LastViewedAtEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldLastViewedAt, v))
}

// LastViewedAtNEQ applies the NEQ predicate on the "last_viewed_at" field.
func LastViewedAtNEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldLastViewedAt, v))
}

// LastViewedAtIn applies the In predicate on the "last_viewed_at" field.
func LastViewedAtIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldLastViewedAt, vs...))
}

// LastViewedAtNotIn applies the NotIn predicate on the "last_viewed_at" field.
func LastViewedAtNotIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldLastViewedAt, vs...))
}

// LastViewedAtGT applies the GT predicate on the "last_viewed_at" field.
func LastViewedAtGT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldLastViewedAt, v))
}

// LastViewedAtGTE applies the GTE predicate on the "last_viewed_at" field.
func LastViewedAtGTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldLastViewedAt, v))
}

// LastViewedAtLT applies the LT predicate on the "last_viewed_at" field.
func LastViewedAtLT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldLastViewedAt, v))
}

// LastViewedAtLTE applies the LTE predicate on the "last_viewed_at" field.
func LastViewedAtLTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldLastViewedAt, v))
}

// LastViewedAtIsNil applies the IsNil predicate on the "last_viewed_at" field.
func LastViewedAtIsNil() predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIsNull(FieldLastViewedAt))
}

// LastViewedAtNotNil applies the NotNil predicate on the "last_viewed_at" field.
func LastViewedAtNotNil() predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotNull(FieldLastViewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RedeemCard {
	return predicate.RedeemCard(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCard) predicate.RedeemCard {
	return predicate.RedeemCard(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCard) predicate.RedeemCard {
	return predicate.RedeemCard(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCard) predicate.RedeemCard {
	return predicate.RedeemCard(sql.NotPredicates(p))
}
