// Code generated by ent, DO NOT EDIT.

package userbalancepackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userbalancepackage type in the database.
	Label = "user_balance_package"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldPaymentOrderID holds the string denoting the payment_order_id field in the database.
	FieldPaymentOrderID = "payment_order_id"
	// FieldWeeklyCreditUsd holds the string denoting the weekly_credit_usd field in the database.
	FieldWeeklyCreditUsd = "weekly_credit_usd"
	// FieldRemainingUsd holds the string denoting the remaining_usd field in the database.
	FieldRemainingUsd = "remaining_usd"
	// FieldCreditedCount holds the string denoting the credited_count field in the database.
	FieldCreditedCount = "credited_count"
	// FieldRefreshCount holds the string denoting the refresh_count field in the database.
	FieldRefreshCount = "refresh_count"
	// FieldRefreshIntervalDays holds the string denoting the refresh_interval_days field in the database.
	FieldRefreshIntervalDays = "refresh_interval_days"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldNextCreditAt holds the string denoting the next_credit_at field in the database.
	FieldNextCreditAt = "next_credit_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userbalancepackage in the database.
	Table = "user_balance_packages"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_balance_packages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userbalancepackage fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPlanID,
	FieldPaymentOrderID,
	FieldWeeklyCreditUsd,
	FieldRemainingUsd,
	FieldCreditedCount,
	FieldRefreshCount,
	FieldRefreshIntervalDays,
	FieldStartsAt,
	FieldNextCreditAt,
	FieldExpiresAt,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRemainingUsd holds the default value on creation for the "remaining_usd" field.
	DefaultRemainingUsd float64
	// DefaultCreditedCount holds the default value on creation for the "credited_count" field.
	DefaultCreditedCount int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserBalancePackage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByPaymentOrderID orders the results by the payment_order_id field.
func ByPaymentOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentOrderID, opts...).ToFunc()
}

// ByWeeklyCreditUsd orders the results by the weekly_credit_usd field.
func ByWeeklyCreditUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyCreditUsd, opts...).ToFunc()
}

// ByRemainingUsd orders the results by the remaining_usd field.
func ByRemainingUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainingUsd, opts...).ToFunc()
}

// ByCreditedCount orders the results by the credited_count field.
func ByCreditedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditedCount, opts...).ToFunc()
}

// ByRefreshCount orders the results by the refresh_count field.
func ByRefreshCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshCount, opts...).ToFunc()
}

// ByRefreshIntervalDays orders the results by the refresh_interval_days field.
func ByRefreshIntervalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshIntervalDays, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByNextCreditAt orders the results by the next_credit_at field.
func ByNextCreditAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextCreditAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
